/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.boehringer.componentcatalog.server.api;

import com.boehringer.componentcatalog.server.model.CatalogItemFilter;
import com.boehringer.componentcatalog.server.model.RestErrorMessage;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
@Validated
@Controller
@Tag(name = "CatalogFilters", description = "CatalogFilters operations.")
public interface CatalogFiltersApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /catalog-filters : List of all CatalogItemFilters.
     * Returns the list of all CatalogItemFilters for the CatalogItems on the Catalog identified by catalogId.&lt;br/&gt; CatalogItemFilters are built based on the contents of the Catalog and its CatalogItems.&lt;br/&gt; Catalog or CatalogItems **with errors** will affect the number and/or contents of the returned CatalogItemFilters. 
     *
     * @param catalogId id for the Catalog. (required)
     * @return A list of CatalogItemFilters. (status code 200)
     *         or Invalid parameters provided on the request. (status code 400)
     *         or Invalid client token on the request. (status code 401)
     *         or Insufficient permissions for the client to access the resource. (status code 403)
     *         or Server error. (status code 500)
     */
    @Operation(
        operationId = "getCatalogFilters",
        summary = "List of all CatalogItemFilters.",
        description = "Returns the list of all CatalogItemFilters for the CatalogItems on the Catalog identified by catalogId.<br/> CatalogItemFilters are built based on the contents of the Catalog and its CatalogItems.<br/> Catalog or CatalogItems **with errors** will affect the number and/or contents of the returned CatalogItemFilters. ",
        tags = { "CatalogFilters" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of CatalogItemFilters.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = CatalogItemFilter.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid parameters provided on the request.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RestErrorMessage.class))
            }),
            @ApiResponse(responseCode = "401", description = "Invalid client token on the request.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RestErrorMessage.class))
            }),
            @ApiResponse(responseCode = "403", description = "Insufficient permissions for the client to access the resource.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RestErrorMessage.class))
            }),
            @ApiResponse(responseCode = "500", description = "Server error.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RestErrorMessage.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/catalog-filters",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<CatalogItemFilter>> getCatalogFilters(
        @NotNull @Parameter(name = "catalogId", description = "id for the Catalog.", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "catalogId", required = true) String catalogId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"label\" : \"business\", \"options\" : [ \"some-business-option\", \"some-other-business-option\" ] }, { \"label\" : \"business\", \"options\" : [ \"some-business-option\", \"some-other-business-option\" ] } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
