/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.boehringer.componentcatalog.server.api;

import com.boehringer.componentcatalog.server.model.FileFormat;
import com.boehringer.componentcatalog.server.model.RestErrorMessage;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-03-19T10:54:28.944058747+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
@Validated
@Controller
@Tag(name = "Files", description = "File operations.")
public interface FilesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /files/{id}/contents : Returns the contents of a File.
     * Returns the contents of a File entity associated to the provided id, unless: &lt;ul&gt; &lt;li&gt;The id is not associated to any File.&lt;/li&gt; &lt;li&gt;Or the associated File is invalid (e.g. corrupted) and can&#39;t be processed to create a response.&lt;/li&gt; &lt;/ul&gt; 
     *
     * @param id id for the File. (required)
     * @param format desired format for the returned File contents, **must** match the actual format. (required)
     * @return File contents, either in binary or text format. (status code 200)
     *         or Invalid client token on the request. (status code 401)
     *         or Insufficient permissions for the client to access the resource. (status code 403)
     *         or No File associated to the provided id. (status code 404)
     *         or Invalid File associated to the provided id. (status code 422)
     *         or Server error. (status code 500)
     */
    @Operation(
        operationId = "getFileById",
        summary = "Returns the contents of a File.",
        description = "Returns the contents of a File entity associated to the provided id, unless: <ul> <li>The id is not associated to any File.</li> <li>Or the associated File is invalid (e.g. corrupted) and can't be processed to create a response.</li> </ul> ",
        tags = { "Files" },
        responses = {
            @ApiResponse(responseCode = "200", description = "File contents, either in binary or text format.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = byte[].class)),
                @Content(mediaType = "text/*", schema = @Schema(implementation = byte[].class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = byte[].class))
            }),
            @ApiResponse(responseCode = "401", description = "Invalid client token on the request.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = RestErrorMessage.class)),
                @Content(mediaType = "text/*", schema = @Schema(implementation = RestErrorMessage.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = RestErrorMessage.class))
            }),
            @ApiResponse(responseCode = "403", description = "Insufficient permissions for the client to access the resource.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = RestErrorMessage.class)),
                @Content(mediaType = "text/*", schema = @Schema(implementation = RestErrorMessage.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = RestErrorMessage.class))
            }),
            @ApiResponse(responseCode = "404", description = "No File associated to the provided id.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = RestErrorMessage.class)),
                @Content(mediaType = "text/*", schema = @Schema(implementation = RestErrorMessage.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = RestErrorMessage.class))
            }),
            @ApiResponse(responseCode = "422", description = "Invalid File associated to the provided id.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = RestErrorMessage.class)),
                @Content(mediaType = "text/*", schema = @Schema(implementation = RestErrorMessage.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = RestErrorMessage.class))
            }),
            @ApiResponse(responseCode = "500", description = "Server error.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = RestErrorMessage.class)),
                @Content(mediaType = "text/*", schema = @Schema(implementation = RestErrorMessage.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = RestErrorMessage.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/files/{id}/contents",
        produces = { "application/octet-stream", "text/*", "application/json" }
    )
    
    default ResponseEntity<byte[]> getFileById(
        @Parameter(name = "id", description = "id for the File.", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @NotNull @Parameter(name = "format", description = "desired format for the returned File contents, **must** match the actual format.", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "format", required = true) FileFormat format
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
