/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AddSshKeyRequest
 */
@JsonPropertyOrder({
  AddSshKeyRequest.JSON_PROPERTY_ALGORITHM_TYPE,
  AddSshKeyRequest.JSON_PROPERTY_BIT_LENGTH,
  AddSshKeyRequest.JSON_PROPERTY_CREATED_DATE,
  AddSshKeyRequest.JSON_PROPERTY_EXPIRY_DAYS,
  AddSshKeyRequest.JSON_PROPERTY_ID,
  AddSshKeyRequest.JSON_PROPERTY_LABEL,
  AddSshKeyRequest.JSON_PROPERTY_LAST_AUTHENTICATED,
  AddSshKeyRequest.JSON_PROPERTY_TEXT
})
@JsonTypeName("addSshKey_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class AddSshKeyRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ALGORITHM_TYPE = "algorithmType";
  @jakarta.annotation.Nullable
  private String algorithmType;

  public static final String JSON_PROPERTY_BIT_LENGTH = "bitLength";
  @jakarta.annotation.Nullable
  private Integer bitLength;

  public static final String JSON_PROPERTY_CREATED_DATE = "createdDate";
  @jakarta.annotation.Nullable
  private OffsetDateTime createdDate;

  public static final String JSON_PROPERTY_EXPIRY_DAYS = "expiryDays";
  @jakarta.annotation.Nullable
  private Integer expiryDays;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_LABEL = "label";
  @jakarta.annotation.Nullable
  private String label;

  public static final String JSON_PROPERTY_LAST_AUTHENTICATED = "lastAuthenticated";
  @jakarta.annotation.Nullable
  private String lastAuthenticated;

  public static final String JSON_PROPERTY_TEXT = "text";
  @jakarta.annotation.Nullable
  private String text;

  public AddSshKeyRequest() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public AddSshKeyRequest(
    @JsonProperty(JSON_PROPERTY_CREATED_DATE) OffsetDateTime createdDate, 
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_LAST_AUTHENTICATED) String lastAuthenticated
  ) {
    this();
    this.createdDate = createdDate;
    this.id = id;
    this.lastAuthenticated = lastAuthenticated;
  }

  public AddSshKeyRequest algorithmType(@jakarta.annotation.Nullable String algorithmType) {
    
    this.algorithmType = algorithmType;
    return this;
  }

  /**
   * Get algorithmType
   * @return algorithmType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALGORITHM_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAlgorithmType() {
    return algorithmType;
  }


  @JsonProperty(JSON_PROPERTY_ALGORITHM_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlgorithmType(@jakarta.annotation.Nullable String algorithmType) {
    this.algorithmType = algorithmType;
  }

  public AddSshKeyRequest bitLength(@jakarta.annotation.Nullable Integer bitLength) {
    
    this.bitLength = bitLength;
    return this;
  }

  /**
   * Get bitLength
   * @return bitLength
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BIT_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBitLength() {
    return bitLength;
  }


  @JsonProperty(JSON_PROPERTY_BIT_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBitLength(@jakarta.annotation.Nullable Integer bitLength) {
    this.bitLength = bitLength;
  }

  /**
   * Get createdDate
   * @return createdDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }



  public AddSshKeyRequest expiryDays(@jakarta.annotation.Nullable Integer expiryDays) {
    
    this.expiryDays = expiryDays;
    return this;
  }

  /**
   * Get expiryDays
   * @return expiryDays
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRY_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getExpiryDays() {
    return expiryDays;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRY_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiryDays(@jakarta.annotation.Nullable Integer expiryDays) {
    this.expiryDays = expiryDays;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  public AddSshKeyRequest label(@jakarta.annotation.Nullable String label) {
    
    this.label = label;
    return this;
  }

  /**
   * Get label
   * @return label
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLabel() {
    return label;
  }


  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabel(@jakarta.annotation.Nullable String label) {
    this.label = label;
  }

  /**
   * Get lastAuthenticated
   * @return lastAuthenticated
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_AUTHENTICATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastAuthenticated() {
    return lastAuthenticated;
  }



  public AddSshKeyRequest text(@jakarta.annotation.Nullable String text) {
    
    this.text = text;
    return this;
  }

  /**
   * Get text
   * @return text
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getText() {
    return text;
  }


  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setText(@jakarta.annotation.Nullable String text) {
    this.text = text;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddSshKeyRequest addSshKeyRequest = (AddSshKeyRequest) o;
    return Objects.equals(this.algorithmType, addSshKeyRequest.algorithmType) &&
        Objects.equals(this.bitLength, addSshKeyRequest.bitLength) &&
        Objects.equals(this.createdDate, addSshKeyRequest.createdDate) &&
        Objects.equals(this.expiryDays, addSshKeyRequest.expiryDays) &&
        Objects.equals(this.id, addSshKeyRequest.id) &&
        Objects.equals(this.label, addSshKeyRequest.label) &&
        Objects.equals(this.lastAuthenticated, addSshKeyRequest.lastAuthenticated) &&
        Objects.equals(this.text, addSshKeyRequest.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(algorithmType, bitLength, createdDate, expiryDays, id, label, lastAuthenticated, text);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddSshKeyRequest {\n");
    sb.append("    algorithmType: ").append(toIndentedString(algorithmType)).append("\n");
    sb.append("    bitLength: ").append(toIndentedString(bitLength)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    expiryDays: ").append(toIndentedString(expiryDays)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    lastAuthenticated: ").append(toIndentedString(lastAuthenticated)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

