/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestReviewerGroup;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetReviewerGroups1200Response
 */
@JsonPropertyOrder({
  GetReviewerGroups1200Response.JSON_PROPERTY_VALUES,
  GetReviewerGroups1200Response.JSON_PROPERTY_SIZE,
  GetReviewerGroups1200Response.JSON_PROPERTY_IS_LAST_PAGE,
  GetReviewerGroups1200Response.JSON_PROPERTY_NEXT_PAGE_START,
  GetReviewerGroups1200Response.JSON_PROPERTY_START,
  GetReviewerGroups1200Response.JSON_PROPERTY_LIMIT
})
@JsonTypeName("getReviewerGroups_1_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T09:35:07.114611322+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class GetReviewerGroups1200Response implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_VALUES = "values";
  @jakarta.annotation.Nullable
  private List<RestReviewerGroup> values = new ArrayList<>();

  public static final String JSON_PROPERTY_SIZE = "size";
  @jakarta.annotation.Nullable
  private BigDecimal size;

  public static final String JSON_PROPERTY_IS_LAST_PAGE = "isLastPage";
  @jakarta.annotation.Nullable
  private Boolean isLastPage;

  public static final String JSON_PROPERTY_NEXT_PAGE_START = "nextPageStart";
  @jakarta.annotation.Nullable
  private Integer nextPageStart;

  public static final String JSON_PROPERTY_START = "start";
  @jakarta.annotation.Nullable
  private Integer start;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @jakarta.annotation.Nullable
  private BigDecimal limit;

  public GetReviewerGroups1200Response() {
  }

  public GetReviewerGroups1200Response values(@jakarta.annotation.Nullable List<RestReviewerGroup> values) {
    
    this.values = values;
    return this;
  }

  public GetReviewerGroups1200Response addValuesItem(RestReviewerGroup valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<>();
    }
    this.values.add(valuesItem);
    return this;
  }

  /**
   * Get values
   * @return values
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RestReviewerGroup> getValues() {
    return values;
  }


  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValues(@jakarta.annotation.Nullable List<RestReviewerGroup> values) {
    this.values = values;
  }

  public GetReviewerGroups1200Response size(@jakarta.annotation.Nullable BigDecimal size) {
    
    this.size = size;
    return this;
  }

  /**
   * Get size
   * @return size
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getSize() {
    return size;
  }


  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSize(@jakarta.annotation.Nullable BigDecimal size) {
    this.size = size;
  }

  public GetReviewerGroups1200Response isLastPage(@jakarta.annotation.Nullable Boolean isLastPage) {
    
    this.isLastPage = isLastPage;
    return this;
  }

  /**
   * Get isLastPage
   * @return isLastPage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_LAST_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsLastPage() {
    return isLastPage;
  }


  @JsonProperty(JSON_PROPERTY_IS_LAST_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsLastPage(@jakarta.annotation.Nullable Boolean isLastPage) {
    this.isLastPage = isLastPage;
  }

  public GetReviewerGroups1200Response nextPageStart(@jakarta.annotation.Nullable Integer nextPageStart) {
    
    this.nextPageStart = nextPageStart;
    return this;
  }

  /**
   * Get nextPageStart
   * @return nextPageStart
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEXT_PAGE_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNextPageStart() {
    return nextPageStart;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_PAGE_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextPageStart(@jakarta.annotation.Nullable Integer nextPageStart) {
    this.nextPageStart = nextPageStart;
  }

  public GetReviewerGroups1200Response start(@jakarta.annotation.Nullable Integer start) {
    
    this.start = start;
    return this;
  }

  /**
   * Get start
   * @return start
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStart() {
    return start;
  }


  @JsonProperty(JSON_PROPERTY_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStart(@jakarta.annotation.Nullable Integer start) {
    this.start = start;
  }

  public GetReviewerGroups1200Response limit(@jakarta.annotation.Nullable BigDecimal limit) {
    
    this.limit = limit;
    return this;
  }

  /**
   * Get limit
   * @return limit
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLimit() {
    return limit;
  }


  @JsonProperty(JSON_PROPERTY_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLimit(@jakarta.annotation.Nullable BigDecimal limit) {
    this.limit = limit;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetReviewerGroups1200Response getReviewerGroups1200Response = (GetReviewerGroups1200Response) o;
    return Objects.equals(this.values, getReviewerGroups1200Response.values) &&
        Objects.equals(this.size, getReviewerGroups1200Response.size) &&
        Objects.equals(this.isLastPage, getReviewerGroups1200Response.isLastPage) &&
        Objects.equals(this.nextPageStart, getReviewerGroups1200Response.nextPageStart) &&
        Objects.equals(this.start, getReviewerGroups1200Response.start) &&
        Objects.equals(this.limit, getReviewerGroups1200Response.limit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(values, size, isLastPage, nextPageStart, start, limit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetReviewerGroups1200Response {\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    isLastPage: ").append(toIndentedString(isLastPage)).append("\n");
    sb.append("    nextPageStart: ").append(toIndentedString(nextPageStart)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

