/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RepositoryPath
 */
@JsonPropertyOrder({
  RepositoryPath.JSON_PROPERTY_COMPONENTS,
  RepositoryPath.JSON_PROPERTY_NAME,
  RepositoryPath.JSON_PROPERTY_TO_STRING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T09:35:07.114611322+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class RepositoryPath implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_COMPONENTS = "components";
  @jakarta.annotation.Nullable
  private List<String> components = new ArrayList<>();

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_TO_STRING = "toString";
  @jakarta.annotation.Nullable
  private String toString;

  public RepositoryPath() {
  }

  public RepositoryPath components(@jakarta.annotation.Nullable List<String> components) {
    
    this.components = components;
    return this;
  }

  public RepositoryPath addComponentsItem(String componentsItem) {
    if (this.components == null) {
      this.components = new ArrayList<>();
    }
    this.components.add(componentsItem);
    return this;
  }

  /**
   * Get components
   * @return components
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPONENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getComponents() {
    return components;
  }


  @JsonProperty(JSON_PROPERTY_COMPONENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComponents(@jakarta.annotation.Nullable List<String> components) {
    this.components = components;
  }

  public RepositoryPath name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public RepositoryPath toString(@jakarta.annotation.Nullable String toString) {
    
    this.toString = toString;
    return this;
  }

  /**
   * Get toString
   * @return toString
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TO_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToString() {
    return toString;
  }


  @JsonProperty(JSON_PROPERTY_TO_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToString(@jakarta.annotation.Nullable String toString) {
    this.toString = toString;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepositoryPath repositoryPath = (RepositoryPath) o;
    return Objects.equals(this.components, repositoryPath.components) &&
        Objects.equals(this.name, repositoryPath.name) &&
        Objects.equals(this.toString, repositoryPath.toString);
  }

  @Override
  public int hashCode() {
    return Objects.hash(components, name, toString);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepositoryPath {\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    toString: ").append(toIndentedString(toString)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

