/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestComment;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestUserReactionCommentAnchor;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestUserReactionCommentAuthor;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestUserReactionCommentParent;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestUserReactionComment
 */
@JsonPropertyOrder({
  RestUserReactionComment.JSON_PROPERTY_ANCHOR,
  RestUserReactionComment.JSON_PROPERTY_UPDATED_DATE,
  RestUserReactionComment.JSON_PROPERTY_CREATED_DATE,
  RestUserReactionComment.JSON_PROPERTY_HTML,
  RestUserReactionComment.JSON_PROPERTY_ANCHORED,
  RestUserReactionComment.JSON_PROPERTY_PENDING,
  RestUserReactionComment.JSON_PROPERTY_REPLY,
  RestUserReactionComment.JSON_PROPERTY_THREAD_RESOLVED,
  RestUserReactionComment.JSON_PROPERTY_AUTHOR,
  RestUserReactionComment.JSON_PROPERTY_VERSION,
  RestUserReactionComment.JSON_PROPERTY_TEXT,
  RestUserReactionComment.JSON_PROPERTY_SEVERITY,
  RestUserReactionComment.JSON_PROPERTY_COMMENTS,
  RestUserReactionComment.JSON_PROPERTY_PARENT,
  RestUserReactionComment.JSON_PROPERTY_ID,
  RestUserReactionComment.JSON_PROPERTY_STATE,
  RestUserReactionComment.JSON_PROPERTY_PROPERTIES
})
@JsonTypeName("RestUserReaction_comment")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T09:35:07.114611322+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class RestUserReactionComment implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ANCHOR = "anchor";
  @jakarta.annotation.Nullable
  private RestUserReactionCommentAnchor anchor;

  public static final String JSON_PROPERTY_UPDATED_DATE = "updatedDate";
  @jakarta.annotation.Nullable
  private Long updatedDate;

  public static final String JSON_PROPERTY_CREATED_DATE = "createdDate";
  @jakarta.annotation.Nullable
  private Long createdDate;

  public static final String JSON_PROPERTY_HTML = "html";
  @jakarta.annotation.Nullable
  private String html;

  public static final String JSON_PROPERTY_ANCHORED = "anchored";
  @jakarta.annotation.Nullable
  private Boolean anchored;

  public static final String JSON_PROPERTY_PENDING = "pending";
  @jakarta.annotation.Nullable
  private Boolean pending;

  public static final String JSON_PROPERTY_REPLY = "reply";
  @jakarta.annotation.Nullable
  private Boolean reply;

  public static final String JSON_PROPERTY_THREAD_RESOLVED = "threadResolved";
  @jakarta.annotation.Nullable
  private Boolean threadResolved;

  public static final String JSON_PROPERTY_AUTHOR = "author";
  @jakarta.annotation.Nullable
  private RestUserReactionCommentAuthor author;

  public static final String JSON_PROPERTY_VERSION = "version";
  @jakarta.annotation.Nullable
  private Integer version;

  public static final String JSON_PROPERTY_TEXT = "text";
  @jakarta.annotation.Nullable
  private String text;

  public static final String JSON_PROPERTY_SEVERITY = "severity";
  @jakarta.annotation.Nullable
  private String severity;

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  @jakarta.annotation.Nullable
  private List<RestComment> comments = new ArrayList<>();

  public static final String JSON_PROPERTY_PARENT = "parent";
  @jakarta.annotation.Nullable
  private RestUserReactionCommentParent parent;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nullable
  private String state;

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  @jakarta.annotation.Nullable
  private Object properties;

  public RestUserReactionComment() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public RestUserReactionComment(
    @JsonProperty(JSON_PROPERTY_UPDATED_DATE) Long updatedDate, 
    @JsonProperty(JSON_PROPERTY_CREATED_DATE) Long createdDate, 
    @JsonProperty(JSON_PROPERTY_HTML) String html, 
    @JsonProperty(JSON_PROPERTY_ANCHORED) Boolean anchored, 
    @JsonProperty(JSON_PROPERTY_PENDING) Boolean pending, 
    @JsonProperty(JSON_PROPERTY_REPLY) Boolean reply, 
    @JsonProperty(JSON_PROPERTY_COMMENTS) List<RestComment> comments
  ) {
    this();
    this.updatedDate = updatedDate;
    this.createdDate = createdDate;
    this.html = html;
    this.anchored = anchored;
    this.pending = pending;
    this.reply = reply;
    this.comments = comments;
  }

  public RestUserReactionComment anchor(@jakarta.annotation.Nullable RestUserReactionCommentAnchor anchor) {
    
    this.anchor = anchor;
    return this;
  }

  /**
   * Get anchor
   * @return anchor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ANCHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestUserReactionCommentAnchor getAnchor() {
    return anchor;
  }


  @JsonProperty(JSON_PROPERTY_ANCHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnchor(@jakarta.annotation.Nullable RestUserReactionCommentAnchor anchor) {
    this.anchor = anchor;
  }

  /**
   * Get updatedDate
   * @return updatedDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUpdatedDate() {
    return updatedDate;
  }



  /**
   * Get createdDate
   * @return createdDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCreatedDate() {
    return createdDate;
  }



  /**
   * Get html
   * @return html
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HTML)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHtml() {
    return html;
  }



  /**
   * Get anchored
   * @return anchored
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ANCHORED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAnchored() {
    return anchored;
  }



  /**
   * Get pending
   * @return pending
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PENDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPending() {
    return pending;
  }



  /**
   * Get reply
   * @return reply
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReply() {
    return reply;
  }



  public RestUserReactionComment threadResolved(@jakarta.annotation.Nullable Boolean threadResolved) {
    
    this.threadResolved = threadResolved;
    return this;
  }

  /**
   * Indicates if this comment thread has been marked as resolved or not
   * @return threadResolved
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THREAD_RESOLVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getThreadResolved() {
    return threadResolved;
  }


  @JsonProperty(JSON_PROPERTY_THREAD_RESOLVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThreadResolved(@jakarta.annotation.Nullable Boolean threadResolved) {
    this.threadResolved = threadResolved;
  }

  public RestUserReactionComment author(@jakarta.annotation.Nullable RestUserReactionCommentAuthor author) {
    
    this.author = author;
    return this;
  }

  /**
   * Get author
   * @return author
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestUserReactionCommentAuthor getAuthor() {
    return author;
  }


  @JsonProperty(JSON_PROPERTY_AUTHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthor(@jakarta.annotation.Nullable RestUserReactionCommentAuthor author) {
    this.author = author;
  }

  public RestUserReactionComment version(@jakarta.annotation.Nullable Integer version) {
    
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(@jakarta.annotation.Nullable Integer version) {
    this.version = version;
  }

  public RestUserReactionComment text(@jakarta.annotation.Nullable String text) {
    
    this.text = text;
    return this;
  }

  /**
   * Get text
   * @return text
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getText() {
    return text;
  }


  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setText(@jakarta.annotation.Nullable String text) {
    this.text = text;
  }

  public RestUserReactionComment severity(@jakarta.annotation.Nullable String severity) {
    
    this.severity = severity;
    return this;
  }

  /**
   * Get severity
   * @return severity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEVERITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSeverity() {
    return severity;
  }


  @JsonProperty(JSON_PROPERTY_SEVERITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeverity(@jakarta.annotation.Nullable String severity) {
    this.severity = severity;
  }

  /**
   * Get comments
   * @return comments
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RestComment> getComments() {
    return comments;
  }



  public RestUserReactionComment parent(@jakarta.annotation.Nullable RestUserReactionCommentParent parent) {
    
    this.parent = parent;
    return this;
  }

  /**
   * Get parent
   * @return parent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestUserReactionCommentParent getParent() {
    return parent;
  }


  @JsonProperty(JSON_PROPERTY_PARENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParent(@jakarta.annotation.Nullable RestUserReactionCommentParent parent) {
    this.parent = parent;
  }

  public RestUserReactionComment id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public RestUserReactionComment state(@jakarta.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@jakarta.annotation.Nullable String state) {
    this.state = state;
  }

  public RestUserReactionComment properties(@jakarta.annotation.Nullable Object properties) {
    
    this.properties = properties;
    return this;
  }

  /**
   * Get properties
   * @return properties
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getProperties() {
    return properties;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProperties(@jakarta.annotation.Nullable Object properties) {
    this.properties = properties;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestUserReactionComment restUserReactionComment = (RestUserReactionComment) o;
    return Objects.equals(this.anchor, restUserReactionComment.anchor) &&
        Objects.equals(this.updatedDate, restUserReactionComment.updatedDate) &&
        Objects.equals(this.createdDate, restUserReactionComment.createdDate) &&
        Objects.equals(this.html, restUserReactionComment.html) &&
        Objects.equals(this.anchored, restUserReactionComment.anchored) &&
        Objects.equals(this.pending, restUserReactionComment.pending) &&
        Objects.equals(this.reply, restUserReactionComment.reply) &&
        Objects.equals(this.threadResolved, restUserReactionComment.threadResolved) &&
        Objects.equals(this.author, restUserReactionComment.author) &&
        Objects.equals(this.version, restUserReactionComment.version) &&
        Objects.equals(this.text, restUserReactionComment.text) &&
        Objects.equals(this.severity, restUserReactionComment.severity) &&
        Objects.equals(this.comments, restUserReactionComment.comments) &&
        Objects.equals(this.parent, restUserReactionComment.parent) &&
        Objects.equals(this.id, restUserReactionComment.id) &&
        Objects.equals(this.state, restUserReactionComment.state) &&
        Objects.equals(this.properties, restUserReactionComment.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(anchor, updatedDate, createdDate, html, anchored, pending, reply, threadResolved, author, version, text, severity, comments, parent, id, state, properties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestUserReactionComment {\n");
    sb.append("    anchor: ").append(toIndentedString(anchor)).append("\n");
    sb.append("    updatedDate: ").append(toIndentedString(updatedDate)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    html: ").append(toIndentedString(html)).append("\n");
    sb.append("    anchored: ").append(toIndentedString(anchored)).append("\n");
    sb.append("    pending: ").append(toIndentedString(pending)).append("\n");
    sb.append("    reply: ").append(toIndentedString(reply)).append("\n");
    sb.append("    threadResolved: ").append(toIndentedString(threadResolved)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

