/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestWebhookCredentials;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.LinkedHashSet;
import java.util.Set;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestWebhook
 */
@JsonPropertyOrder({
  RestWebhook.JSON_PROPERTY_ACTIVE,
  RestWebhook.JSON_PROPERTY_SSL_VERIFICATION_REQUIRED,
  RestWebhook.JSON_PROPERTY_STATISTICS,
  RestWebhook.JSON_PROPERTY_SCOPE_TYPE,
  RestWebhook.JSON_PROPERTY_EVENTS,
  RestWebhook.JSON_PROPERTY_CONFIGURATION,
  RestWebhook.JSON_PROPERTY_URL,
  RestWebhook.JSON_PROPERTY_CREDENTIALS,
  RestWebhook.JSON_PROPERTY_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestWebhook implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  @jakarta.annotation.Nullable
  private Boolean active;

  public static final String JSON_PROPERTY_SSL_VERIFICATION_REQUIRED = "sslVerificationRequired";
  @jakarta.annotation.Nullable
  private Boolean sslVerificationRequired;

  public static final String JSON_PROPERTY_STATISTICS = "statistics";
  @jakarta.annotation.Nullable
  private Object statistics;

  public static final String JSON_PROPERTY_SCOPE_TYPE = "scopeType";
  @jakarta.annotation.Nullable
  private String scopeType;

  public static final String JSON_PROPERTY_EVENTS = "events";
  @jakarta.annotation.Nullable
  private Set<String> events = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_CONFIGURATION = "configuration";
  @jakarta.annotation.Nullable
  private Object _configuration;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_CREDENTIALS = "credentials";
  @jakarta.annotation.Nullable
  private RestWebhookCredentials credentials;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public RestWebhook() {
  }

  public RestWebhook active(@jakarta.annotation.Nullable Boolean active) {
    
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActive() {
    return active;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActive(@jakarta.annotation.Nullable Boolean active) {
    this.active = active;
  }

  public RestWebhook sslVerificationRequired(@jakarta.annotation.Nullable Boolean sslVerificationRequired) {
    
    this.sslVerificationRequired = sslVerificationRequired;
    return this;
  }

  /**
   * Get sslVerificationRequired
   * @return sslVerificationRequired
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SSL_VERIFICATION_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSslVerificationRequired() {
    return sslVerificationRequired;
  }


  @JsonProperty(JSON_PROPERTY_SSL_VERIFICATION_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSslVerificationRequired(@jakarta.annotation.Nullable Boolean sslVerificationRequired) {
    this.sslVerificationRequired = sslVerificationRequired;
  }

  public RestWebhook statistics(@jakarta.annotation.Nullable Object statistics) {
    
    this.statistics = statistics;
    return this;
  }

  /**
   * Get statistics
   * @return statistics
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATISTICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getStatistics() {
    return statistics;
  }


  @JsonProperty(JSON_PROPERTY_STATISTICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatistics(@jakarta.annotation.Nullable Object statistics) {
    this.statistics = statistics;
  }

  public RestWebhook scopeType(@jakarta.annotation.Nullable String scopeType) {
    
    this.scopeType = scopeType;
    return this;
  }

  /**
   * Get scopeType
   * @return scopeType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCOPE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScopeType() {
    return scopeType;
  }


  @JsonProperty(JSON_PROPERTY_SCOPE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScopeType(@jakarta.annotation.Nullable String scopeType) {
    this.scopeType = scopeType;
  }

  public RestWebhook events(@jakarta.annotation.Nullable Set<String> events) {
    
    this.events = events;
    return this;
  }

  public RestWebhook addEventsItem(String eventsItem) {
    if (this.events == null) {
      this.events = new LinkedHashSet<>();
    }
    this.events.add(eventsItem);
    return this;
  }

  /**
   * Get events
   * @return events
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<String> getEvents() {
    return events;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvents(@jakarta.annotation.Nullable Set<String> events) {
    this.events = events;
  }

  public RestWebhook _configuration(@jakarta.annotation.Nullable Object _configuration) {
    
    this._configuration = _configuration;
    return this;
  }

  /**
   * Get _configuration
   * @return _configuration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getConfiguration() {
    return _configuration;
  }


  @JsonProperty(JSON_PROPERTY_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfiguration(@jakarta.annotation.Nullable Object _configuration) {
    this._configuration = _configuration;
  }

  public RestWebhook url(@jakarta.annotation.Nullable String url) {
    
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = url;
  }

  public RestWebhook credentials(@jakarta.annotation.Nullable RestWebhookCredentials credentials) {
    
    this.credentials = credentials;
    return this;
  }

  /**
   * Get credentials
   * @return credentials
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREDENTIALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestWebhookCredentials getCredentials() {
    return credentials;
  }


  @JsonProperty(JSON_PROPERTY_CREDENTIALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredentials(@jakarta.annotation.Nullable RestWebhookCredentials credentials) {
    this.credentials = credentials;
  }

  public RestWebhook name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestWebhook restWebhook = (RestWebhook) o;
    return Objects.equals(this.active, restWebhook.active) &&
        Objects.equals(this.sslVerificationRequired, restWebhook.sslVerificationRequired) &&
        Objects.equals(this.statistics, restWebhook.statistics) &&
        Objects.equals(this.scopeType, restWebhook.scopeType) &&
        Objects.equals(this.events, restWebhook.events) &&
        Objects.equals(this._configuration, restWebhook._configuration) &&
        Objects.equals(this.url, restWebhook.url) &&
        Objects.equals(this.credentials, restWebhook.credentials) &&
        Objects.equals(this.name, restWebhook.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, sslVerificationRequired, statistics, scopeType, events, _configuration, url, credentials, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestWebhook {\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    sslVerificationRequired: ").append(toIndentedString(sslVerificationRequired)).append("\n");
    sb.append("    statistics: ").append(toIndentedString(statistics)).append("\n");
    sb.append("    scopeType: ").append(toIndentedString(scopeType)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    credentials: ").append(toIndentedString(credentials)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

