/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestTag
 */
@JsonPropertyOrder({
  RestTag.JSON_PROPERTY_HASH,
  RestTag.JSON_PROPERTY_LATEST_COMMIT,
  RestTag.JSON_PROPERTY_LATEST_CHANGESET,
  RestTag.JSON_PROPERTY_DISPLAY_ID,
  RestTag.JSON_PROPERTY_ID,
  RestTag.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestTag implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_HASH = "hash";
  @jakarta.annotation.Nullable
  private String hash;

  public static final String JSON_PROPERTY_LATEST_COMMIT = "latestCommit";
  @jakarta.annotation.Nullable
  private String latestCommit;

  public static final String JSON_PROPERTY_LATEST_CHANGESET = "latestChangeset";
  @jakarta.annotation.Nullable
  private String latestChangeset;

  public static final String JSON_PROPERTY_DISPLAY_ID = "displayId";
  @jakarta.annotation.Nullable
  private String displayId;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    BRANCH(String.valueOf("BRANCH")),
    
    TAG(String.valueOf("TAG"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type;

  public RestTag() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public RestTag(
    @JsonProperty(JSON_PROPERTY_LATEST_COMMIT) String latestCommit, 
    @JsonProperty(JSON_PROPERTY_LATEST_CHANGESET) String latestChangeset
  ) {
    this();
    this.latestCommit = latestCommit;
    this.latestChangeset = latestChangeset;
  }

  public RestTag hash(@jakarta.annotation.Nullable String hash) {
    
    this.hash = hash;
    return this;
  }

  /**
   * Get hash
   * @return hash
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHash() {
    return hash;
  }


  @JsonProperty(JSON_PROPERTY_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHash(@jakarta.annotation.Nullable String hash) {
    this.hash = hash;
  }

  /**
   * Get latestCommit
   * @return latestCommit
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LATEST_COMMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLatestCommit() {
    return latestCommit;
  }



  /**
   * Get latestChangeset
   * @return latestChangeset
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LATEST_CHANGESET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLatestChangeset() {
    return latestChangeset;
  }



  public RestTag displayId(@jakarta.annotation.Nullable String displayId) {
    
    this.displayId = displayId;
    return this;
  }

  /**
   * Get displayId
   * @return displayId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayId() {
    return displayId;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayId(@jakarta.annotation.Nullable String displayId) {
    this.displayId = displayId;
  }

  public RestTag id(@jakarta.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }

  public RestTag type(@jakarta.annotation.Nullable TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestTag restTag = (RestTag) o;
    return Objects.equals(this.hash, restTag.hash) &&
        Objects.equals(this.latestCommit, restTag.latestCommit) &&
        Objects.equals(this.latestChangeset, restTag.latestChangeset) &&
        Objects.equals(this.displayId, restTag.displayId) &&
        Objects.equals(this.id, restTag.id) &&
        Objects.equals(this.type, restTag.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hash, latestCommit, latestChangeset, displayId, id, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestTag {\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    latestCommit: ").append(toIndentedString(latestCommit)).append("\n");
    sb.append("    latestChangeset: ").append(toIndentedString(latestChangeset)).append("\n");
    sb.append("    displayId: ").append(toIndentedString(displayId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

