/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestPullRequestFromRefRepositoryProject
 */
@JsonPropertyOrder({
  RestPullRequestFromRefRepositoryProject.JSON_PROPERTY_AVATAR,
  RestPullRequestFromRefRepositoryProject.JSON_PROPERTY_AVATAR_URL,
  RestPullRequestFromRefRepositoryProject.JSON_PROPERTY_DESCRIPTION,
  RestPullRequestFromRefRepositoryProject.JSON_PROPERTY_NAMESPACE,
  RestPullRequestFromRefRepositoryProject.JSON_PROPERTY_SCOPE,
  RestPullRequestFromRefRepositoryProject.JSON_PROPERTY_NAME,
  RestPullRequestFromRefRepositoryProject.JSON_PROPERTY_KEY,
  RestPullRequestFromRefRepositoryProject.JSON_PROPERTY_ID,
  RestPullRequestFromRefRepositoryProject.JSON_PROPERTY_TYPE,
  RestPullRequestFromRefRepositoryProject.JSON_PROPERTY_PUBLIC,
  RestPullRequestFromRefRepositoryProject.JSON_PROPERTY_LINKS
})
@JsonTypeName("RestPullRequest_fromRef_repository_project")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T09:35:07.114611322+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class RestPullRequestFromRefRepositoryProject implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_AVATAR = "avatar";
  @jakarta.annotation.Nullable
  private String avatar;

  public static final String JSON_PROPERTY_AVATAR_URL = "avatarUrl";
  @jakarta.annotation.Nullable
  private String avatarUrl;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_NAMESPACE = "namespace";
  @jakarta.annotation.Nullable
  private String namespace;

  public static final String JSON_PROPERTY_SCOPE = "scope";
  @jakarta.annotation.Nullable
  private String scope;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_KEY = "key";
  @jakarta.annotation.Nonnull
  private String key;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    NORMAL(String.valueOf("NORMAL")),
    
    PERSONAL(String.valueOf("PERSONAL"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type;

  public static final String JSON_PROPERTY_PUBLIC = "public";
  @jakarta.annotation.Nullable
  private Boolean _public;

  public static final String JSON_PROPERTY_LINKS = "links";
  @jakarta.annotation.Nullable
  private Object links;

  public RestPullRequestFromRefRepositoryProject() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public RestPullRequestFromRefRepositoryProject(
    @JsonProperty(JSON_PROPERTY_DESCRIPTION) String description, 
    @JsonProperty(JSON_PROPERTY_NAMESPACE) String namespace, 
    @JsonProperty(JSON_PROPERTY_SCOPE) String scope, 
    @JsonProperty(JSON_PROPERTY_NAME) String name, 
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_TYPE) TypeEnum type, 
    @JsonProperty(JSON_PROPERTY_PUBLIC) Boolean _public
  ) {
    this();
    this.description = description;
    this.namespace = namespace;
    this.scope = scope;
    this.name = name;
    this.id = id;
    this.type = type;
    this._public = _public;
  }

  public RestPullRequestFromRefRepositoryProject avatar(@jakarta.annotation.Nullable String avatar) {
    
    this.avatar = avatar;
    return this;
  }

  /**
   * Get avatar
   * @return avatar
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVATAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAvatar() {
    return avatar;
  }


  @JsonProperty(JSON_PROPERTY_AVATAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvatar(@jakarta.annotation.Nullable String avatar) {
    this.avatar = avatar;
  }

  public RestPullRequestFromRefRepositoryProject avatarUrl(@jakarta.annotation.Nullable String avatarUrl) {
    
    this.avatarUrl = avatarUrl;
    return this;
  }

  /**
   * Get avatarUrl
   * @return avatarUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVATAR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAvatarUrl() {
    return avatarUrl;
  }


  @JsonProperty(JSON_PROPERTY_AVATAR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvatarUrl(@jakarta.annotation.Nullable String avatarUrl) {
    this.avatarUrl = avatarUrl;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }



  /**
   * Get namespace
   * @return namespace
   * @deprecated
   */
  @Deprecated
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAMESPACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNamespace() {
    return namespace;
  }



  /**
   * Get scope
   * @return scope
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScope() {
    return scope;
  }



  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }



  public RestPullRequestFromRefRepositoryProject key(@jakarta.annotation.Nonnull String key) {
    
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKey() {
    return key;
  }


  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKey(@jakarta.annotation.Nonnull String key) {
    this.key = key;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }



  /**
   * Get _public
   * @return _public
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPublic() {
    return _public;
  }



  public RestPullRequestFromRefRepositoryProject links(@jakarta.annotation.Nullable Object links) {
    
    this.links = links;
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(@jakarta.annotation.Nullable Object links) {
    this.links = links;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestPullRequestFromRefRepositoryProject restPullRequestFromRefRepositoryProject = (RestPullRequestFromRefRepositoryProject) o;
    return Objects.equals(this.avatar, restPullRequestFromRefRepositoryProject.avatar) &&
        Objects.equals(this.avatarUrl, restPullRequestFromRefRepositoryProject.avatarUrl) &&
        Objects.equals(this.description, restPullRequestFromRefRepositoryProject.description) &&
        Objects.equals(this.namespace, restPullRequestFromRefRepositoryProject.namespace) &&
        Objects.equals(this.scope, restPullRequestFromRefRepositoryProject.scope) &&
        Objects.equals(this.name, restPullRequestFromRefRepositoryProject.name) &&
        Objects.equals(this.key, restPullRequestFromRefRepositoryProject.key) &&
        Objects.equals(this.id, restPullRequestFromRefRepositoryProject.id) &&
        Objects.equals(this.type, restPullRequestFromRefRepositoryProject.type) &&
        Objects.equals(this._public, restPullRequestFromRefRepositoryProject._public) &&
        Objects.equals(this.links, restPullRequestFromRefRepositoryProject.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(avatar, avatarUrl, description, namespace, scope, name, key, id, type, _public, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestPullRequestFromRefRepositoryProject {\n");
    sb.append("    avatar: ").append(toIndentedString(avatar)).append("\n");
    sb.append("    avatarUrl: ").append(toIndentedString(avatarUrl)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    _public: ").append(toIndentedString(_public)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

