/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestApplicationUser;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestPullRequestConditionScope;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.UpdatePullRequestCondition1RequestSourceMatcher;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestPullRequestCondition
 */
@JsonPropertyOrder({
  RestPullRequestCondition.JSON_PROPERTY_SOURCE_REF_MATCHER,
  RestPullRequestCondition.JSON_PROPERTY_REVIEWERS,
  RestPullRequestCondition.JSON_PROPERTY_TARGET_REF_MATCHER,
  RestPullRequestCondition.JSON_PROPERTY_SCOPE,
  RestPullRequestCondition.JSON_PROPERTY_REQUIRED_APPROVALS,
  RestPullRequestCondition.JSON_PROPERTY_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T09:35:07.114611322+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class RestPullRequestCondition implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SOURCE_REF_MATCHER = "sourceRefMatcher";
  @jakarta.annotation.Nullable
  private UpdatePullRequestCondition1RequestSourceMatcher sourceRefMatcher;

  public static final String JSON_PROPERTY_REVIEWERS = "reviewers";
  @jakarta.annotation.Nullable
  private List<RestApplicationUser> reviewers = new ArrayList<>();

  public static final String JSON_PROPERTY_TARGET_REF_MATCHER = "targetRefMatcher";
  @jakarta.annotation.Nullable
  private UpdatePullRequestCondition1RequestSourceMatcher targetRefMatcher;

  public static final String JSON_PROPERTY_SCOPE = "scope";
  @jakarta.annotation.Nullable
  private RestPullRequestConditionScope scope;

  public static final String JSON_PROPERTY_REQUIRED_APPROVALS = "requiredApprovals";
  @jakarta.annotation.Nullable
  private Integer requiredApprovals;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public RestPullRequestCondition() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public RestPullRequestCondition(
    @JsonProperty(JSON_PROPERTY_ID) Integer id
  ) {
    this();
    this.id = id;
  }

  public RestPullRequestCondition sourceRefMatcher(@jakarta.annotation.Nullable UpdatePullRequestCondition1RequestSourceMatcher sourceRefMatcher) {
    
    this.sourceRefMatcher = sourceRefMatcher;
    return this;
  }

  /**
   * Get sourceRefMatcher
   * @return sourceRefMatcher
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_REF_MATCHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdatePullRequestCondition1RequestSourceMatcher getSourceRefMatcher() {
    return sourceRefMatcher;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_REF_MATCHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceRefMatcher(@jakarta.annotation.Nullable UpdatePullRequestCondition1RequestSourceMatcher sourceRefMatcher) {
    this.sourceRefMatcher = sourceRefMatcher;
  }

  public RestPullRequestCondition reviewers(@jakarta.annotation.Nullable List<RestApplicationUser> reviewers) {
    
    this.reviewers = reviewers;
    return this;
  }

  public RestPullRequestCondition addReviewersItem(RestApplicationUser reviewersItem) {
    if (this.reviewers == null) {
      this.reviewers = new ArrayList<>();
    }
    this.reviewers.add(reviewersItem);
    return this;
  }

  /**
   * Get reviewers
   * @return reviewers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REVIEWERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RestApplicationUser> getReviewers() {
    return reviewers;
  }


  @JsonProperty(JSON_PROPERTY_REVIEWERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReviewers(@jakarta.annotation.Nullable List<RestApplicationUser> reviewers) {
    this.reviewers = reviewers;
  }

  public RestPullRequestCondition targetRefMatcher(@jakarta.annotation.Nullable UpdatePullRequestCondition1RequestSourceMatcher targetRefMatcher) {
    
    this.targetRefMatcher = targetRefMatcher;
    return this;
  }

  /**
   * Get targetRefMatcher
   * @return targetRefMatcher
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TARGET_REF_MATCHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdatePullRequestCondition1RequestSourceMatcher getTargetRefMatcher() {
    return targetRefMatcher;
  }


  @JsonProperty(JSON_PROPERTY_TARGET_REF_MATCHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetRefMatcher(@jakarta.annotation.Nullable UpdatePullRequestCondition1RequestSourceMatcher targetRefMatcher) {
    this.targetRefMatcher = targetRefMatcher;
  }

  public RestPullRequestCondition scope(@jakarta.annotation.Nullable RestPullRequestConditionScope scope) {
    
    this.scope = scope;
    return this;
  }

  /**
   * Get scope
   * @return scope
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestPullRequestConditionScope getScope() {
    return scope;
  }


  @JsonProperty(JSON_PROPERTY_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScope(@jakarta.annotation.Nullable RestPullRequestConditionScope scope) {
    this.scope = scope;
  }

  public RestPullRequestCondition requiredApprovals(@jakarta.annotation.Nullable Integer requiredApprovals) {
    
    this.requiredApprovals = requiredApprovals;
    return this;
  }

  /**
   * Get requiredApprovals
   * @return requiredApprovals
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REQUIRED_APPROVALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRequiredApprovals() {
    return requiredApprovals;
  }


  @JsonProperty(JSON_PROPERTY_REQUIRED_APPROVALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequiredApprovals(@jakarta.annotation.Nullable Integer requiredApprovals) {
    this.requiredApprovals = requiredApprovals;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestPullRequestCondition restPullRequestCondition = (RestPullRequestCondition) o;
    return Objects.equals(this.sourceRefMatcher, restPullRequestCondition.sourceRefMatcher) &&
        Objects.equals(this.reviewers, restPullRequestCondition.reviewers) &&
        Objects.equals(this.targetRefMatcher, restPullRequestCondition.targetRefMatcher) &&
        Objects.equals(this.scope, restPullRequestCondition.scope) &&
        Objects.equals(this.requiredApprovals, restPullRequestCondition.requiredApprovals) &&
        Objects.equals(this.id, restPullRequestCondition.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceRefMatcher, reviewers, targetRefMatcher, scope, requiredApprovals, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestPullRequestCondition {\n");
    sb.append("    sourceRefMatcher: ").append(toIndentedString(sourceRefMatcher)).append("\n");
    sb.append("    reviewers: ").append(toIndentedString(reviewers)).append("\n");
    sb.append("    targetRefMatcher: ").append(toIndentedString(targetRefMatcher)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    requiredApprovals: ").append(toIndentedString(requiredApprovals)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

