/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestEmoticon
 */
@JsonPropertyOrder({
  RestEmoticon.JSON_PROPERTY_SHORTCUT,
  RestEmoticon.JSON_PROPERTY_URL,
  RestEmoticon.JSON_PROPERTY_VALUE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T09:35:07.114611322+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class RestEmoticon implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SHORTCUT = "shortcut";
  @jakarta.annotation.Nullable
  private String shortcut;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_VALUE = "value";
  @jakarta.annotation.Nullable
  private String value;

  public RestEmoticon() {
  }

  public RestEmoticon shortcut(@jakarta.annotation.Nullable String shortcut) {
    
    this.shortcut = shortcut;
    return this;
  }

  /**
   * Get shortcut
   * @return shortcut
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHORTCUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getShortcut() {
    return shortcut;
  }


  @JsonProperty(JSON_PROPERTY_SHORTCUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShortcut(@jakarta.annotation.Nullable String shortcut) {
    this.shortcut = shortcut;
  }

  public RestEmoticon url(@jakarta.annotation.Nullable String url) {
    
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = url;
  }

  public RestEmoticon value(@jakarta.annotation.Nullable String value) {
    
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@jakarta.annotation.Nullable String value) {
    this.value = value;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestEmoticon restEmoticon = (RestEmoticon) o;
    return Objects.equals(this.shortcut, restEmoticon.shortcut) &&
        Objects.equals(this.url, restEmoticon.url) &&
        Objects.equals(this.value, restEmoticon.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shortcut, url, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestEmoticon {\n");
    sb.append("    shortcut: ").append(toIndentedString(shortcut)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

