/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestMeshNode
 */
@JsonPropertyOrder({
  RestMeshNode.JSON_PROPERTY_RPC_URL,
  RestMeshNode.JSON_PROPERTY_LAST_SEEN_DATE,
  RestMeshNode.JSON_PROPERTY_RPC_ID,
  RestMeshNode.JSON_PROPERTY_OFFLINE,
  RestMeshNode.JSON_PROPERTY_NAME,
  RestMeshNode.JSON_PROPERTY_ID,
  RestMeshNode.JSON_PROPERTY_STATE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestMeshNode implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_RPC_URL = "rpcUrl";
  @jakarta.annotation.Nullable
  private String rpcUrl;

  public static final String JSON_PROPERTY_LAST_SEEN_DATE = "lastSeenDate";
  @jakarta.annotation.Nullable
  private BigDecimal lastSeenDate;

  public static final String JSON_PROPERTY_RPC_ID = "rpcId";
  @jakarta.annotation.Nullable
  private String rpcId;

  public static final String JSON_PROPERTY_OFFLINE = "offline";
  @jakarta.annotation.Nullable
  private Boolean offline;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  /**
   * Gets or Sets state
   */
  public enum StateEnum {
    AVAILABLE(String.valueOf("AVAILABLE")),
    
    DELETING(String.valueOf("DELETING")),
    
    DISABLED(String.valueOf("DISABLED")),
    
    DRAINING(String.valueOf("DRAINING")),
    
    OFFLINE(String.valueOf("OFFLINE"));

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nullable
  private StateEnum state;

  public RestMeshNode() {
  }

  public RestMeshNode rpcUrl(@jakarta.annotation.Nullable String rpcUrl) {
    
    this.rpcUrl = rpcUrl;
    return this;
  }

  /**
   * Get rpcUrl
   * @return rpcUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RPC_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRpcUrl() {
    return rpcUrl;
  }


  @JsonProperty(JSON_PROPERTY_RPC_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRpcUrl(@jakarta.annotation.Nullable String rpcUrl) {
    this.rpcUrl = rpcUrl;
  }

  public RestMeshNode lastSeenDate(@jakarta.annotation.Nullable BigDecimal lastSeenDate) {
    
    this.lastSeenDate = lastSeenDate;
    return this;
  }

  /**
   * Get lastSeenDate
   * @return lastSeenDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_SEEN_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLastSeenDate() {
    return lastSeenDate;
  }


  @JsonProperty(JSON_PROPERTY_LAST_SEEN_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastSeenDate(@jakarta.annotation.Nullable BigDecimal lastSeenDate) {
    this.lastSeenDate = lastSeenDate;
  }

  public RestMeshNode rpcId(@jakarta.annotation.Nullable String rpcId) {
    
    this.rpcId = rpcId;
    return this;
  }

  /**
   * Get rpcId
   * @return rpcId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RPC_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRpcId() {
    return rpcId;
  }


  @JsonProperty(JSON_PROPERTY_RPC_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRpcId(@jakarta.annotation.Nullable String rpcId) {
    this.rpcId = rpcId;
  }

  public RestMeshNode offline(@jakarta.annotation.Nullable Boolean offline) {
    
    this.offline = offline;
    return this;
  }

  /**
   * Get offline
   * @return offline
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OFFLINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOffline() {
    return offline;
  }


  @JsonProperty(JSON_PROPERTY_OFFLINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOffline(@jakarta.annotation.Nullable Boolean offline) {
    this.offline = offline;
  }

  public RestMeshNode name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public RestMeshNode id(@jakarta.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }

  public RestMeshNode state(@jakarta.annotation.Nullable StateEnum state) {
    
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StateEnum getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@jakarta.annotation.Nullable StateEnum state) {
    this.state = state;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestMeshNode restMeshNode = (RestMeshNode) o;
    return Objects.equals(this.rpcUrl, restMeshNode.rpcUrl) &&
        Objects.equals(this.lastSeenDate, restMeshNode.lastSeenDate) &&
        Objects.equals(this.rpcId, restMeshNode.rpcId) &&
        Objects.equals(this.offline, restMeshNode.offline) &&
        Objects.equals(this.name, restMeshNode.name) &&
        Objects.equals(this.id, restMeshNode.id) &&
        Objects.equals(this.state, restMeshNode.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rpcUrl, lastSeenDate, rpcId, offline, name, id, state);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestMeshNode {\n");
    sb.append("    rpcUrl: ").append(toIndentedString(rpcUrl)).append("\n");
    sb.append("    lastSeenDate: ").append(toIndentedString(lastSeenDate)).append("\n");
    sb.append("    rpcId: ").append(toIndentedString(rpcId)).append("\n");
    sb.append("    offline: ").append(toIndentedString(offline)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

