/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestChangesetChanges;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestChangesetFromCommit;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestChangesetToCommit;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestPullRequestFromRefRepository;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestChangeset
 */
@JsonPropertyOrder({
  RestChangeset.JSON_PROPERTY_CHANGES,
  RestChangeset.JSON_PROPERTY_TO_COMMIT,
  RestChangeset.JSON_PROPERTY_FROM_COMMIT,
  RestChangeset.JSON_PROPERTY_REPOSITORY,
  RestChangeset.JSON_PROPERTY_LINKS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestChangeset implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CHANGES = "changes";
  @jakarta.annotation.Nullable
  private RestChangesetChanges changes;

  public static final String JSON_PROPERTY_TO_COMMIT = "toCommit";
  @jakarta.annotation.Nullable
  private RestChangesetToCommit toCommit;

  public static final String JSON_PROPERTY_FROM_COMMIT = "fromCommit";
  @jakarta.annotation.Nullable
  private RestChangesetFromCommit fromCommit;

  public static final String JSON_PROPERTY_REPOSITORY = "repository";
  @jakarta.annotation.Nullable
  private RestPullRequestFromRefRepository repository;

  public static final String JSON_PROPERTY_LINKS = "links";
  @jakarta.annotation.Nullable
  private Object links;

  public RestChangeset() {
  }

  public RestChangeset changes(@jakarta.annotation.Nullable RestChangesetChanges changes) {
    
    this.changes = changes;
    return this;
  }

  /**
   * Get changes
   * @return changes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestChangesetChanges getChanges() {
    return changes;
  }


  @JsonProperty(JSON_PROPERTY_CHANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChanges(@jakarta.annotation.Nullable RestChangesetChanges changes) {
    this.changes = changes;
  }

  public RestChangeset toCommit(@jakarta.annotation.Nullable RestChangesetToCommit toCommit) {
    
    this.toCommit = toCommit;
    return this;
  }

  /**
   * Get toCommit
   * @return toCommit
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TO_COMMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestChangesetToCommit getToCommit() {
    return toCommit;
  }


  @JsonProperty(JSON_PROPERTY_TO_COMMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToCommit(@jakarta.annotation.Nullable RestChangesetToCommit toCommit) {
    this.toCommit = toCommit;
  }

  public RestChangeset fromCommit(@jakarta.annotation.Nullable RestChangesetFromCommit fromCommit) {
    
    this.fromCommit = fromCommit;
    return this;
  }

  /**
   * Get fromCommit
   * @return fromCommit
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FROM_COMMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestChangesetFromCommit getFromCommit() {
    return fromCommit;
  }


  @JsonProperty(JSON_PROPERTY_FROM_COMMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromCommit(@jakarta.annotation.Nullable RestChangesetFromCommit fromCommit) {
    this.fromCommit = fromCommit;
  }

  public RestChangeset repository(@jakarta.annotation.Nullable RestPullRequestFromRefRepository repository) {
    
    this.repository = repository;
    return this;
  }

  /**
   * Get repository
   * @return repository
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPOSITORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestPullRequestFromRefRepository getRepository() {
    return repository;
  }


  @JsonProperty(JSON_PROPERTY_REPOSITORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepository(@jakarta.annotation.Nullable RestPullRequestFromRefRepository repository) {
    this.repository = repository;
  }

  public RestChangeset links(@jakarta.annotation.Nullable Object links) {
    
    this.links = links;
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(@jakarta.annotation.Nullable Object links) {
    this.links = links;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestChangeset restChangeset = (RestChangeset) o;
    return Objects.equals(this.changes, restChangeset.changes) &&
        Objects.equals(this.toCommit, restChangeset.toCommit) &&
        Objects.equals(this.fromCommit, restChangeset.fromCommit) &&
        Objects.equals(this.repository, restChangeset.repository) &&
        Objects.equals(this.links, restChangeset.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changes, toCommit, fromCommit, repository, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestChangeset {\n");
    sb.append("    changes: ").append(toIndentedString(changes)).append("\n");
    sb.append("    toCommit: ").append(toIndentedString(toCommit)).append("\n");
    sb.append("    fromCommit: ").append(toIndentedString(fromCommit)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

