/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestPullRequestFromRefRepository;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestPullRequestFromRefRepositoryProject;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestSshAccessKeyKey;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestSshAccessKey
 */
@JsonPropertyOrder({
  RestSshAccessKey.JSON_PROPERTY_PROJECT,
  RestSshAccessKey.JSON_PROPERTY_REPOSITORY,
  RestSshAccessKey.JSON_PROPERTY_KEY,
  RestSshAccessKey.JSON_PROPERTY_PERMISSION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T09:35:07.114611322+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class RestSshAccessKey implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_PROJECT = "project";
  @jakarta.annotation.Nullable
  private RestPullRequestFromRefRepositoryProject project;

  public static final String JSON_PROPERTY_REPOSITORY = "repository";
  @jakarta.annotation.Nullable
  private RestPullRequestFromRefRepository repository;

  public static final String JSON_PROPERTY_KEY = "key";
  @jakarta.annotation.Nullable
  private RestSshAccessKeyKey key;

  /**
   * Gets or Sets permission
   */
  public enum PermissionEnum {
    USER_ADMIN(String.valueOf("USER_ADMIN")),
    
    PROJECT_VIEW(String.valueOf("PROJECT_VIEW")),
    
    REPO_READ(String.valueOf("REPO_READ")),
    
    REPO_WRITE(String.valueOf("REPO_WRITE")),
    
    REPO_ADMIN(String.valueOf("REPO_ADMIN")),
    
    PROJECT_READ(String.valueOf("PROJECT_READ")),
    
    PROJECT_WRITE(String.valueOf("PROJECT_WRITE")),
    
    REPO_CREATE(String.valueOf("REPO_CREATE")),
    
    PROJECT_ADMIN(String.valueOf("PROJECT_ADMIN")),
    
    LICENSED_USER(String.valueOf("LICENSED_USER")),
    
    PROJECT_CREATE(String.valueOf("PROJECT_CREATE")),
    
    ADMIN(String.valueOf("ADMIN")),
    
    SYS_ADMIN(String.valueOf("SYS_ADMIN"));

    private String value;

    PermissionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PermissionEnum fromValue(String value) {
      for (PermissionEnum b : PermissionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PERMISSION = "permission";
  @jakarta.annotation.Nullable
  private PermissionEnum permission;

  public RestSshAccessKey() {
  }

  public RestSshAccessKey project(@jakarta.annotation.Nullable RestPullRequestFromRefRepositoryProject project) {
    
    this.project = project;
    return this;
  }

  /**
   * Get project
   * @return project
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestPullRequestFromRefRepositoryProject getProject() {
    return project;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProject(@jakarta.annotation.Nullable RestPullRequestFromRefRepositoryProject project) {
    this.project = project;
  }

  public RestSshAccessKey repository(@jakarta.annotation.Nullable RestPullRequestFromRefRepository repository) {
    
    this.repository = repository;
    return this;
  }

  /**
   * Get repository
   * @return repository
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPOSITORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestPullRequestFromRefRepository getRepository() {
    return repository;
  }


  @JsonProperty(JSON_PROPERTY_REPOSITORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepository(@jakarta.annotation.Nullable RestPullRequestFromRefRepository repository) {
    this.repository = repository;
  }

  public RestSshAccessKey key(@jakarta.annotation.Nullable RestSshAccessKeyKey key) {
    
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestSshAccessKeyKey getKey() {
    return key;
  }


  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKey(@jakarta.annotation.Nullable RestSshAccessKeyKey key) {
    this.key = key;
  }

  public RestSshAccessKey permission(@jakarta.annotation.Nullable PermissionEnum permission) {
    
    this.permission = permission;
    return this;
  }

  /**
   * Get permission
   * @return permission
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERMISSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PermissionEnum getPermission() {
    return permission;
  }


  @JsonProperty(JSON_PROPERTY_PERMISSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermission(@jakarta.annotation.Nullable PermissionEnum permission) {
    this.permission = permission;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestSshAccessKey restSshAccessKey = (RestSshAccessKey) o;
    return Objects.equals(this.project, restSshAccessKey.project) &&
        Objects.equals(this.repository, restSshAccessKey.repository) &&
        Objects.equals(this.key, restSshAccessKey.key) &&
        Objects.equals(this.permission, restSshAccessKey.permission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(project, repository, key, permission);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestSshAccessKey {\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

