/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestNodeConnectivityReportNode;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestNodeConnectivitySummarySummary;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestNodeConnectivitySummary
 */
@JsonPropertyOrder({
  RestNodeConnectivitySummary.JSON_PROPERTY_SUMMARY,
  RestNodeConnectivitySummary.JSON_PROPERTY_NODE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestNodeConnectivitySummary implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @jakarta.annotation.Nullable
  private RestNodeConnectivitySummarySummary summary;

  public static final String JSON_PROPERTY_NODE = "node";
  @jakarta.annotation.Nullable
  private RestNodeConnectivityReportNode node;

  public RestNodeConnectivitySummary() {
  }

  public RestNodeConnectivitySummary summary(@jakarta.annotation.Nullable RestNodeConnectivitySummarySummary summary) {
    
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestNodeConnectivitySummarySummary getSummary() {
    return summary;
  }


  @JsonProperty(JSON_PROPERTY_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSummary(@jakarta.annotation.Nullable RestNodeConnectivitySummarySummary summary) {
    this.summary = summary;
  }

  public RestNodeConnectivitySummary node(@jakarta.annotation.Nullable RestNodeConnectivityReportNode node) {
    
    this.node = node;
    return this;
  }

  /**
   * Get node
   * @return node
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestNodeConnectivityReportNode getNode() {
    return node;
  }


  @JsonProperty(JSON_PROPERTY_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNode(@jakarta.annotation.Nullable RestNodeConnectivityReportNode node) {
    this.node = node;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestNodeConnectivitySummary restNodeConnectivitySummary = (RestNodeConnectivitySummary) o;
    return Objects.equals(this.summary, restNodeConnectivitySummary.summary) &&
        Objects.equals(this.node, restNodeConnectivitySummary.node);
  }

  @Override
  public int hashCode() {
    return Objects.hash(summary, node);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestNodeConnectivitySummary {\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    node: ").append(toIndentedString(node)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

