/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestMeshMigrationSummary
 */
@JsonPropertyOrder({
  RestMeshMigrationSummary.JSON_PROPERTY_JOB_ID,
  RestMeshMigrationSummary.JSON_PROPERTY_END_TIME,
  RestMeshMigrationSummary.JSON_PROPERTY_MAX_BANDWIDTH,
  RestMeshMigrationSummary.JSON_PROPERTY_PROGRESS,
  RestMeshMigrationSummary.JSON_PROPERTY_START_TIME,
  RestMeshMigrationSummary.JSON_PROPERTY_QUEUE,
  RestMeshMigrationSummary.JSON_PROPERTY_STATE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T09:35:07.114611322+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class RestMeshMigrationSummary implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_JOB_ID = "jobId";
  @jakarta.annotation.Nullable
  private Long jobId;

  public static final String JSON_PROPERTY_END_TIME = "endTime";
  @jakarta.annotation.Nullable
  private Long endTime;

  public static final String JSON_PROPERTY_MAX_BANDWIDTH = "maxBandwidth";
  @jakarta.annotation.Nullable
  private Long maxBandwidth;

  public static final String JSON_PROPERTY_PROGRESS = "progress";
  @jakarta.annotation.Nullable
  private Integer progress;

  public static final String JSON_PROPERTY_START_TIME = "startTime";
  @jakarta.annotation.Nullable
  private Long startTime;

  public static final String JSON_PROPERTY_QUEUE = "queue";
  @jakarta.annotation.Nullable
  private Object queue;

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nullable
  private String state;

  public RestMeshMigrationSummary() {
  }

  public RestMeshMigrationSummary jobId(@jakarta.annotation.Nullable Long jobId) {
    
    this.jobId = jobId;
    return this;
  }

  /**
   * Get jobId
   * @return jobId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobId() {
    return jobId;
  }


  @JsonProperty(JSON_PROPERTY_JOB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJobId(@jakarta.annotation.Nullable Long jobId) {
    this.jobId = jobId;
  }

  public RestMeshMigrationSummary endTime(@jakarta.annotation.Nullable Long endTime) {
    
    this.endTime = endTime;
    return this;
  }

  /**
   * Get endTime
   * @return endTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getEndTime() {
    return endTime;
  }


  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTime(@jakarta.annotation.Nullable Long endTime) {
    this.endTime = endTime;
  }

  public RestMeshMigrationSummary maxBandwidth(@jakarta.annotation.Nullable Long maxBandwidth) {
    
    this.maxBandwidth = maxBandwidth;
    return this;
  }

  /**
   * Get maxBandwidth
   * @return maxBandwidth
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAX_BANDWIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMaxBandwidth() {
    return maxBandwidth;
  }


  @JsonProperty(JSON_PROPERTY_MAX_BANDWIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxBandwidth(@jakarta.annotation.Nullable Long maxBandwidth) {
    this.maxBandwidth = maxBandwidth;
  }

  public RestMeshMigrationSummary progress(@jakarta.annotation.Nullable Integer progress) {
    
    this.progress = progress;
    return this;
  }

  /**
   * Get progress
   * @return progress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROGRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProgress() {
    return progress;
  }


  @JsonProperty(JSON_PROPERTY_PROGRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProgress(@jakarta.annotation.Nullable Integer progress) {
    this.progress = progress;
  }

  public RestMeshMigrationSummary startTime(@jakarta.annotation.Nullable Long startTime) {
    
    this.startTime = startTime;
    return this;
  }

  /**
   * Get startTime
   * @return startTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getStartTime() {
    return startTime;
  }


  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(@jakarta.annotation.Nullable Long startTime) {
    this.startTime = startTime;
  }

  public RestMeshMigrationSummary queue(@jakarta.annotation.Nullable Object queue) {
    
    this.queue = queue;
    return this;
  }

  /**
   * Get queue
   * @return queue
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUEUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getQueue() {
    return queue;
  }


  @JsonProperty(JSON_PROPERTY_QUEUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQueue(@jakarta.annotation.Nullable Object queue) {
    this.queue = queue;
  }

  public RestMeshMigrationSummary state(@jakarta.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@jakarta.annotation.Nullable String state) {
    this.state = state;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestMeshMigrationSummary restMeshMigrationSummary = (RestMeshMigrationSummary) o;
    return Objects.equals(this.jobId, restMeshMigrationSummary.jobId) &&
        Objects.equals(this.endTime, restMeshMigrationSummary.endTime) &&
        Objects.equals(this.maxBandwidth, restMeshMigrationSummary.maxBandwidth) &&
        Objects.equals(this.progress, restMeshMigrationSummary.progress) &&
        Objects.equals(this.startTime, restMeshMigrationSummary.startTime) &&
        Objects.equals(this.queue, restMeshMigrationSummary.queue) &&
        Objects.equals(this.state, restMeshMigrationSummary.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobId, endTime, maxBandwidth, progress, startTime, queue, state);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestMeshMigrationSummary {\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    maxBandwidth: ").append(toIndentedString(maxBandwidth)).append("\n");
    sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    queue: ").append(toIndentedString(queue)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

