/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestApplySuggestionRequestCommentVersion
 */
@JsonPropertyOrder({
  RestApplySuggestionRequestCommentVersion.JSON_PROPERTY_AS_INT,
  RestApplySuggestionRequestCommentVersion.JSON_PROPERTY_PRESENT
})
@JsonTypeName("RestApplySuggestionRequest_commentVersion")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T09:35:07.114611322+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class RestApplySuggestionRequestCommentVersion implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_AS_INT = "asInt";
  @jakarta.annotation.Nullable
  private Integer asInt;

  public static final String JSON_PROPERTY_PRESENT = "present";
  @jakarta.annotation.Nullable
  private Boolean present;

  public RestApplySuggestionRequestCommentVersion() {
  }

  public RestApplySuggestionRequestCommentVersion asInt(@jakarta.annotation.Nullable Integer asInt) {
    
    this.asInt = asInt;
    return this;
  }

  /**
   * Get asInt
   * @return asInt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AS_INT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAsInt() {
    return asInt;
  }


  @JsonProperty(JSON_PROPERTY_AS_INT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAsInt(@jakarta.annotation.Nullable Integer asInt) {
    this.asInt = asInt;
  }

  public RestApplySuggestionRequestCommentVersion present(@jakarta.annotation.Nullable Boolean present) {
    
    this.present = present;
    return this;
  }

  /**
   * Get present
   * @return present
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRESENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPresent() {
    return present;
  }


  @JsonProperty(JSON_PROPERTY_PRESENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPresent(@jakarta.annotation.Nullable Boolean present) {
    this.present = present;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestApplySuggestionRequestCommentVersion restApplySuggestionRequestCommentVersion = (RestApplySuggestionRequestCommentVersion) o;
    return Objects.equals(this.asInt, restApplySuggestionRequestCommentVersion.asInt) &&
        Objects.equals(this.present, restApplySuggestionRequestCommentVersion.present);
  }

  @Override
  public int hashCode() {
    return Objects.hash(asInt, present);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestApplySuggestionRequestCommentVersion {\n");
    sb.append("    asInt: ").append(toIndentedString(asInt)).append("\n");
    sb.append("    present: ").append(toIndentedString(present)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

