/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestGitTagCreateRequest
 */
@JsonPropertyOrder({
  RestGitTagCreateRequest.JSON_PROPERTY_FORCE,
  RestGitTagCreateRequest.JSON_PROPERTY_MESSAGE,
  RestGitTagCreateRequest.JSON_PROPERTY_NAME,
  RestGitTagCreateRequest.JSON_PROPERTY_START_POINT,
  RestGitTagCreateRequest.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestGitTagCreateRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_FORCE = "force";
  @jakarta.annotation.Nullable
  private Boolean force;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_START_POINT = "startPoint";
  @jakarta.annotation.Nullable
  private String startPoint;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    ANNOTATED(String.valueOf("ANNOTATED")),
    
    LIGHTWEIGHT(String.valueOf("LIGHTWEIGHT"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type;

  public RestGitTagCreateRequest() {
  }

  public RestGitTagCreateRequest force(@jakarta.annotation.Nullable Boolean force) {
    
    this.force = force;
    return this;
  }

  /**
   * Get force
   * @return force
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FORCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getForce() {
    return force;
  }


  @JsonProperty(JSON_PROPERTY_FORCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setForce(@jakarta.annotation.Nullable Boolean force) {
    this.force = force;
  }

  public RestGitTagCreateRequest message(@jakarta.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@jakarta.annotation.Nullable String message) {
    this.message = message;
  }

  public RestGitTagCreateRequest name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public RestGitTagCreateRequest startPoint(@jakarta.annotation.Nullable String startPoint) {
    
    this.startPoint = startPoint;
    return this;
  }

  /**
   * Get startPoint
   * @return startPoint
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_POINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStartPoint() {
    return startPoint;
  }


  @JsonProperty(JSON_PROPERTY_START_POINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartPoint(@jakarta.annotation.Nullable String startPoint) {
    this.startPoint = startPoint;
  }

  public RestGitTagCreateRequest type(@jakarta.annotation.Nullable TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestGitTagCreateRequest restGitTagCreateRequest = (RestGitTagCreateRequest) o;
    return Objects.equals(this.force, restGitTagCreateRequest.force) &&
        Objects.equals(this.message, restGitTagCreateRequest.message) &&
        Objects.equals(this.name, restGitTagCreateRequest.name) &&
        Objects.equals(this.startPoint, restGitTagCreateRequest.startPoint) &&
        Objects.equals(this.type, restGitTagCreateRequest.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(force, message, name, startPoint, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestGitTagCreateRequest {\n");
    sb.append("    force: ").append(toIndentedString(force)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    startPoint: ").append(toIndentedString(startPoint)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

