/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestBranch
 */
@JsonPropertyOrder({
  RestBranch.JSON_PROPERTY_DISPLAY_ID,
  RestBranch.JSON_PROPERTY_DEFAULT,
  RestBranch.JSON_PROPERTY_TYPE,
  RestBranch.JSON_PROPERTY_LATEST_COMMIT,
  RestBranch.JSON_PROPERTY_LATEST_CHANGESET,
  RestBranch.JSON_PROPERTY_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T09:35:07.114611322+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class RestBranch implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_DISPLAY_ID = "displayId";
  @jakarta.annotation.Nullable
  private String displayId;

  public static final String JSON_PROPERTY_DEFAULT = "default";
  @jakarta.annotation.Nullable
  private Boolean _default;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private JsonNullable<Object> type = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_LATEST_COMMIT = "latestCommit";
  @jakarta.annotation.Nullable
  private String latestCommit;

  public static final String JSON_PROPERTY_LATEST_CHANGESET = "latestChangeset";
  @jakarta.annotation.Nullable
  private String latestChangeset;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public RestBranch() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public RestBranch(
    @JsonProperty(JSON_PROPERTY_DISPLAY_ID) String displayId, 
    @JsonProperty(JSON_PROPERTY_DEFAULT) Boolean _default, 
    @JsonProperty(JSON_PROPERTY_LATEST_COMMIT) String latestCommit, 
    @JsonProperty(JSON_PROPERTY_LATEST_CHANGESET) String latestChangeset
  ) {
    this();
    this.displayId = displayId;
    this._default = _default;
    this.latestCommit = latestCommit;
    this.latestChangeset = latestChangeset;
  }

  /**
   * Get displayId
   * @return displayId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayId() {
    return displayId;
  }



  /**
   * Get _default
   * @return _default
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDefault() {
    return _default;
  }



  public RestBranch type(@jakarta.annotation.Nullable Object type) {
    this.type = JsonNullable.<Object>of(type);
    
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Object getType() {
        return type.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getType_JsonNullable() {
    return type;
  }
  
  @JsonProperty(JSON_PROPERTY_TYPE)
  public void setType_JsonNullable(JsonNullable<Object> type) {
    this.type = type;
  }

  public void setType(@jakarta.annotation.Nullable Object type) {
    this.type = JsonNullable.<Object>of(type);
  }

  /**
   * Get latestCommit
   * @return latestCommit
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LATEST_COMMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLatestCommit() {
    return latestCommit;
  }



  /**
   * Get latestChangeset
   * @return latestChangeset
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LATEST_CHANGESET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLatestChangeset() {
    return latestChangeset;
  }



  public RestBranch id(@jakarta.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestBranch restBranch = (RestBranch) o;
    return Objects.equals(this.displayId, restBranch.displayId) &&
        Objects.equals(this._default, restBranch._default) &&
        equalsNullable(this.type, restBranch.type) &&
        Objects.equals(this.latestCommit, restBranch.latestCommit) &&
        Objects.equals(this.latestChangeset, restBranch.latestChangeset) &&
        Objects.equals(this.id, restBranch.id);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayId, _default, hashCodeNullable(type), latestCommit, latestChangeset, id);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestBranch {\n");
    sb.append("    displayId: ").append(toIndentedString(displayId)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    latestCommit: ").append(toIndentedString(latestCommit)).append("\n");
    sb.append("    latestChangeset: ").append(toIndentedString(latestChangeset)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

