/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.SimpleSshKeyFingerprint;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestSshSettings
 */
@JsonPropertyOrder({
  RestSshSettings.JSON_PROPERTY_ACCESS_KEYS_ENABLED,
  RestSshSettings.JSON_PROPERTY_FINGERPRINT,
  RestSshSettings.JSON_PROPERTY_ENABLED,
  RestSshSettings.JSON_PROPERTY_BASE_URL,
  RestSshSettings.JSON_PROPERTY_PORT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestSshSettings implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ACCESS_KEYS_ENABLED = "accessKeysEnabled";
  @jakarta.annotation.Nullable
  private Boolean accessKeysEnabled;

  public static final String JSON_PROPERTY_FINGERPRINT = "fingerprint";
  @jakarta.annotation.Nullable
  private SimpleSshKeyFingerprint fingerprint;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  @jakarta.annotation.Nullable
  private Boolean enabled;

  public static final String JSON_PROPERTY_BASE_URL = "baseUrl";
  @jakarta.annotation.Nullable
  private String baseUrl;

  public static final String JSON_PROPERTY_PORT = "port";
  @jakarta.annotation.Nullable
  private Integer port;

  public RestSshSettings() {
  }

  public RestSshSettings accessKeysEnabled(@jakarta.annotation.Nullable Boolean accessKeysEnabled) {
    
    this.accessKeysEnabled = accessKeysEnabled;
    return this;
  }

  /**
   * Get accessKeysEnabled
   * @return accessKeysEnabled
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_KEYS_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAccessKeysEnabled() {
    return accessKeysEnabled;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_KEYS_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessKeysEnabled(@jakarta.annotation.Nullable Boolean accessKeysEnabled) {
    this.accessKeysEnabled = accessKeysEnabled;
  }

  public RestSshSettings fingerprint(@jakarta.annotation.Nullable SimpleSshKeyFingerprint fingerprint) {
    
    this.fingerprint = fingerprint;
    return this;
  }

  /**
   * Get fingerprint
   * @return fingerprint
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINGERPRINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SimpleSshKeyFingerprint getFingerprint() {
    return fingerprint;
  }


  @JsonProperty(JSON_PROPERTY_FINGERPRINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFingerprint(@jakarta.annotation.Nullable SimpleSshKeyFingerprint fingerprint) {
    this.fingerprint = fingerprint;
  }

  public RestSshSettings enabled(@jakarta.annotation.Nullable Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }

  public RestSshSettings baseUrl(@jakarta.annotation.Nullable String baseUrl) {
    
    this.baseUrl = baseUrl;
    return this;
  }

  /**
   * Get baseUrl
   * @return baseUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BASE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBaseUrl() {
    return baseUrl;
  }


  @JsonProperty(JSON_PROPERTY_BASE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBaseUrl(@jakarta.annotation.Nullable String baseUrl) {
    this.baseUrl = baseUrl;
  }

  public RestSshSettings port(@jakarta.annotation.Nullable Integer port) {
    
    this.port = port;
    return this;
  }

  /**
   * Get port
   * @return port
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPort() {
    return port;
  }


  @JsonProperty(JSON_PROPERTY_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPort(@jakarta.annotation.Nullable Integer port) {
    this.port = port;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestSshSettings restSshSettings = (RestSshSettings) o;
    return Objects.equals(this.accessKeysEnabled, restSshSettings.accessKeysEnabled) &&
        Objects.equals(this.fingerprint, restSshSettings.fingerprint) &&
        Objects.equals(this.enabled, restSshSettings.enabled) &&
        Objects.equals(this.baseUrl, restSshSettings.baseUrl) &&
        Objects.equals(this.port, restSshSettings.port);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessKeysEnabled, fingerprint, enabled, baseUrl, port);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestSshSettings {\n");
    sb.append("    accessKeysEnabled: ").append(toIndentedString(accessKeysEnabled)).append("\n");
    sb.append("    fingerprint: ").append(toIndentedString(fingerprint)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    baseUrl: ").append(toIndentedString(baseUrl)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

