/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestApplySuggestionRequestCommentVersion;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestApplySuggestionRequestPullRequestVersion;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestApplySuggestionRequestSuggestionIndex;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestApplySuggestionRequest
 */
@JsonPropertyOrder({
  RestApplySuggestionRequest.JSON_PROPERTY_COMMENT_VERSION,
  RestApplySuggestionRequest.JSON_PROPERTY_COMMIT_MESSAGE,
  RestApplySuggestionRequest.JSON_PROPERTY_PULL_REQUEST_VERSION,
  RestApplySuggestionRequest.JSON_PROPERTY_SUGGESTION_INDEX
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestApplySuggestionRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_COMMENT_VERSION = "commentVersion";
  @jakarta.annotation.Nullable
  private RestApplySuggestionRequestCommentVersion commentVersion;

  public static final String JSON_PROPERTY_COMMIT_MESSAGE = "commitMessage";
  @jakarta.annotation.Nullable
  private String commitMessage;

  public static final String JSON_PROPERTY_PULL_REQUEST_VERSION = "pullRequestVersion";
  @jakarta.annotation.Nullable
  private RestApplySuggestionRequestPullRequestVersion pullRequestVersion;

  public static final String JSON_PROPERTY_SUGGESTION_INDEX = "suggestionIndex";
  @jakarta.annotation.Nullable
  private RestApplySuggestionRequestSuggestionIndex suggestionIndex;

  public RestApplySuggestionRequest() {
  }

  public RestApplySuggestionRequest commentVersion(@jakarta.annotation.Nullable RestApplySuggestionRequestCommentVersion commentVersion) {
    
    this.commentVersion = commentVersion;
    return this;
  }

  /**
   * Get commentVersion
   * @return commentVersion
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENT_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestApplySuggestionRequestCommentVersion getCommentVersion() {
    return commentVersion;
  }


  @JsonProperty(JSON_PROPERTY_COMMENT_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommentVersion(@jakarta.annotation.Nullable RestApplySuggestionRequestCommentVersion commentVersion) {
    this.commentVersion = commentVersion;
  }

  public RestApplySuggestionRequest commitMessage(@jakarta.annotation.Nullable String commitMessage) {
    
    this.commitMessage = commitMessage;
    return this;
  }

  /**
   * Get commitMessage
   * @return commitMessage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMIT_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCommitMessage() {
    return commitMessage;
  }


  @JsonProperty(JSON_PROPERTY_COMMIT_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommitMessage(@jakarta.annotation.Nullable String commitMessage) {
    this.commitMessage = commitMessage;
  }

  public RestApplySuggestionRequest pullRequestVersion(@jakarta.annotation.Nullable RestApplySuggestionRequestPullRequestVersion pullRequestVersion) {
    
    this.pullRequestVersion = pullRequestVersion;
    return this;
  }

  /**
   * Get pullRequestVersion
   * @return pullRequestVersion
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PULL_REQUEST_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestApplySuggestionRequestPullRequestVersion getPullRequestVersion() {
    return pullRequestVersion;
  }


  @JsonProperty(JSON_PROPERTY_PULL_REQUEST_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPullRequestVersion(@jakarta.annotation.Nullable RestApplySuggestionRequestPullRequestVersion pullRequestVersion) {
    this.pullRequestVersion = pullRequestVersion;
  }

  public RestApplySuggestionRequest suggestionIndex(@jakarta.annotation.Nullable RestApplySuggestionRequestSuggestionIndex suggestionIndex) {
    
    this.suggestionIndex = suggestionIndex;
    return this;
  }

  /**
   * Get suggestionIndex
   * @return suggestionIndex
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUGGESTION_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestApplySuggestionRequestSuggestionIndex getSuggestionIndex() {
    return suggestionIndex;
  }


  @JsonProperty(JSON_PROPERTY_SUGGESTION_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuggestionIndex(@jakarta.annotation.Nullable RestApplySuggestionRequestSuggestionIndex suggestionIndex) {
    this.suggestionIndex = suggestionIndex;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestApplySuggestionRequest restApplySuggestionRequest = (RestApplySuggestionRequest) o;
    return Objects.equals(this.commentVersion, restApplySuggestionRequest.commentVersion) &&
        Objects.equals(this.commitMessage, restApplySuggestionRequest.commitMessage) &&
        Objects.equals(this.pullRequestVersion, restApplySuggestionRequest.pullRequestVersion) &&
        Objects.equals(this.suggestionIndex, restApplySuggestionRequest.suggestionIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commentVersion, commitMessage, pullRequestVersion, suggestionIndex);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestApplySuggestionRequest {\n");
    sb.append("    commentVersion: ").append(toIndentedString(commentVersion)).append("\n");
    sb.append("    commitMessage: ").append(toIndentedString(commitMessage)).append("\n");
    sb.append("    pullRequestVersion: ").append(toIndentedString(pullRequestVersion)).append("\n");
    sb.append("    suggestionIndex: ").append(toIndentedString(suggestionIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

