/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestNodeConnectivityReportNode;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestNodeConnectivitySummary;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestNodeConnectivityReport
 */
@JsonPropertyOrder({
  RestNodeConnectivityReport.JSON_PROPERTY_SUMMARIES,
  RestNodeConnectivityReport.JSON_PROPERTY_NODE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestNodeConnectivityReport implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SUMMARIES = "summaries";
  @jakarta.annotation.Nullable
  private List<RestNodeConnectivitySummary> summaries = new ArrayList<>();

  public static final String JSON_PROPERTY_NODE = "node";
  @jakarta.annotation.Nullable
  private RestNodeConnectivityReportNode node;

  public RestNodeConnectivityReport() {
  }

  public RestNodeConnectivityReport summaries(@jakarta.annotation.Nullable List<RestNodeConnectivitySummary> summaries) {
    
    this.summaries = summaries;
    return this;
  }

  public RestNodeConnectivityReport addSummariesItem(RestNodeConnectivitySummary summariesItem) {
    if (this.summaries == null) {
      this.summaries = new ArrayList<>();
    }
    this.summaries.add(summariesItem);
    return this;
  }

  /**
   * Get summaries
   * @return summaries
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUMMARIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RestNodeConnectivitySummary> getSummaries() {
    return summaries;
  }


  @JsonProperty(JSON_PROPERTY_SUMMARIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSummaries(@jakarta.annotation.Nullable List<RestNodeConnectivitySummary> summaries) {
    this.summaries = summaries;
  }

  public RestNodeConnectivityReport node(@jakarta.annotation.Nullable RestNodeConnectivityReportNode node) {
    
    this.node = node;
    return this;
  }

  /**
   * Get node
   * @return node
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestNodeConnectivityReportNode getNode() {
    return node;
  }


  @JsonProperty(JSON_PROPERTY_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNode(@jakarta.annotation.Nullable RestNodeConnectivityReportNode node) {
    this.node = node;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestNodeConnectivityReport restNodeConnectivityReport = (RestNodeConnectivityReport) o;
    return Objects.equals(this.summaries, restNodeConnectivityReport.summaries) &&
        Objects.equals(this.node, restNodeConnectivityReport.node);
  }

  @Override
  public int hashCode() {
    return Objects.hash(summaries, node);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestNodeConnectivityReport {\n");
    sb.append("    summaries: ").append(toIndentedString(summaries)).append("\n");
    sb.append("    node: ").append(toIndentedString(node)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

