/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestSecretScanningRuleSetRequest
 */
@JsonPropertyOrder({
  RestSecretScanningRuleSetRequest.JSON_PROPERTY_LINE_REGEX,
  RestSecretScanningRuleSetRequest.JSON_PROPERTY_NAME,
  RestSecretScanningRuleSetRequest.JSON_PROPERTY_PATH_REGEX
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T09:35:07.114611322+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class RestSecretScanningRuleSetRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_LINE_REGEX = "lineRegex";
  @jakarta.annotation.Nullable
  private String lineRegex;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_PATH_REGEX = "pathRegex";
  @jakarta.annotation.Nullable
  private String pathRegex;

  public RestSecretScanningRuleSetRequest() {
  }

  public RestSecretScanningRuleSetRequest lineRegex(@jakarta.annotation.Nullable String lineRegex) {
    
    this.lineRegex = lineRegex;
    return this;
  }

  /**
   * Regular expression for matching a secret on a code line
   * @return lineRegex
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINE_REGEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLineRegex() {
    return lineRegex;
  }


  @JsonProperty(JSON_PROPERTY_LINE_REGEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLineRegex(@jakarta.annotation.Nullable String lineRegex) {
    this.lineRegex = lineRegex;
  }

  public RestSecretScanningRuleSetRequest name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Human readable name for the rule
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public RestSecretScanningRuleSetRequest pathRegex(@jakarta.annotation.Nullable String pathRegex) {
    
    this.pathRegex = pathRegex;
    return this;
  }

  /**
   * Regular expression matching file names
   * @return pathRegex
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PATH_REGEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPathRegex() {
    return pathRegex;
  }


  @JsonProperty(JSON_PROPERTY_PATH_REGEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPathRegex(@jakarta.annotation.Nullable String pathRegex) {
    this.pathRegex = pathRegex;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestSecretScanningRuleSetRequest restSecretScanningRuleSetRequest = (RestSecretScanningRuleSetRequest) o;
    return Objects.equals(this.lineRegex, restSecretScanningRuleSetRequest.lineRegex) &&
        Objects.equals(this.name, restSecretScanningRuleSetRequest.name) &&
        Objects.equals(this.pathRegex, restSecretScanningRuleSetRequest.pathRegex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lineRegex, name, pathRegex);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestSecretScanningRuleSetRequest {\n");
    sb.append("    lineRegex: ").append(toIndentedString(lineRegex)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pathRegex: ").append(toIndentedString(pathRegex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

