/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestBulkUserRateLimitSettingsUpdateRequestSettings;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestPullRequestParticipantUser;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestUserRateLimitSettings
 */
@JsonPropertyOrder({
  RestUserRateLimitSettings.JSON_PROPERTY_WHITELISTED,
  RestUserRateLimitSettings.JSON_PROPERTY_USER,
  RestUserRateLimitSettings.JSON_PROPERTY_SETTINGS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestUserRateLimitSettings implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_WHITELISTED = "whitelisted";
  @jakarta.annotation.Nullable
  private Boolean whitelisted;

  public static final String JSON_PROPERTY_USER = "user";
  @jakarta.annotation.Nullable
  private RestPullRequestParticipantUser user;

  public static final String JSON_PROPERTY_SETTINGS = "settings";
  @jakarta.annotation.Nullable
  private RestBulkUserRateLimitSettingsUpdateRequestSettings settings;

  public RestUserRateLimitSettings() {
  }

  public RestUserRateLimitSettings whitelisted(@jakarta.annotation.Nullable Boolean whitelisted) {
    
    this.whitelisted = whitelisted;
    return this;
  }

  /**
   * Get whitelisted
   * @return whitelisted
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WHITELISTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getWhitelisted() {
    return whitelisted;
  }


  @JsonProperty(JSON_PROPERTY_WHITELISTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWhitelisted(@jakarta.annotation.Nullable Boolean whitelisted) {
    this.whitelisted = whitelisted;
  }

  public RestUserRateLimitSettings user(@jakarta.annotation.Nullable RestPullRequestParticipantUser user) {
    
    this.user = user;
    return this;
  }

  /**
   * Get user
   * @return user
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestPullRequestParticipantUser getUser() {
    return user;
  }


  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUser(@jakarta.annotation.Nullable RestPullRequestParticipantUser user) {
    this.user = user;
  }

  public RestUserRateLimitSettings settings(@jakarta.annotation.Nullable RestBulkUserRateLimitSettingsUpdateRequestSettings settings) {
    
    this.settings = settings;
    return this;
  }

  /**
   * Get settings
   * @return settings
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestBulkUserRateLimitSettingsUpdateRequestSettings getSettings() {
    return settings;
  }


  @JsonProperty(JSON_PROPERTY_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSettings(@jakarta.annotation.Nullable RestBulkUserRateLimitSettingsUpdateRequestSettings settings) {
    this.settings = settings;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestUserRateLimitSettings restUserRateLimitSettings = (RestUserRateLimitSettings) o;
    return Objects.equals(this.whitelisted, restUserRateLimitSettings.whitelisted) &&
        Objects.equals(this.user, restUserRateLimitSettings.user) &&
        Objects.equals(this.settings, restUserRateLimitSettings.settings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(whitelisted, user, settings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestUserRateLimitSettings {\n");
    sb.append("    whitelisted: ").append(toIndentedString(whitelisted)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

