/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestPullRequestFromRefRepositoryOrigin;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestPullRequestFromRefRepositoryProject;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestLabelable
 */
@JsonPropertyOrder({
  RestLabelable.JSON_PROPERTY_LABELABLE_TYPE,
  RestLabelable.JSON_PROPERTY_HIERARCHY_ID,
  RestLabelable.JSON_PROPERTY_SCM_ID,
  RestLabelable.JSON_PROPERTY_SLUG,
  RestLabelable.JSON_PROPERTY_STATUS_MESSAGE,
  RestLabelable.JSON_PROPERTY_ARCHIVED,
  RestLabelable.JSON_PROPERTY_FORKABLE,
  RestLabelable.JSON_PROPERTY_DEFAULT_BRANCH,
  RestLabelable.JSON_PROPERTY_PARTITION,
  RestLabelable.JSON_PROPERTY_RELATED_LINKS,
  RestLabelable.JSON_PROPERTY_PROJECT,
  RestLabelable.JSON_PROPERTY_DESCRIPTION,
  RestLabelable.JSON_PROPERTY_SCOPE,
  RestLabelable.JSON_PROPERTY_ORIGIN,
  RestLabelable.JSON_PROPERTY_NAME,
  RestLabelable.JSON_PROPERTY_ID,
  RestLabelable.JSON_PROPERTY_STATE,
  RestLabelable.JSON_PROPERTY_PUBLIC,
  RestLabelable.JSON_PROPERTY_LINKS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T09:35:07.114611322+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class RestLabelable implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * Gets or Sets labelableType
   */
  public enum LabelableTypeEnum {
    REPOSITORY(String.valueOf("REPOSITORY"));

    private String value;

    LabelableTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LabelableTypeEnum fromValue(String value) {
      for (LabelableTypeEnum b : LabelableTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LABELABLE_TYPE = "labelableType";
  @jakarta.annotation.Nullable
  private LabelableTypeEnum labelableType;

  public static final String JSON_PROPERTY_HIERARCHY_ID = "hierarchyId";
  @jakarta.annotation.Nullable
  private String hierarchyId;

  public static final String JSON_PROPERTY_SCM_ID = "scmId";
  @jakarta.annotation.Nullable
  private String scmId;

  public static final String JSON_PROPERTY_SLUG = "slug";
  @jakarta.annotation.Nullable
  private String slug;

  public static final String JSON_PROPERTY_STATUS_MESSAGE = "statusMessage";
  @jakarta.annotation.Nullable
  private String statusMessage;

  public static final String JSON_PROPERTY_ARCHIVED = "archived";
  @jakarta.annotation.Nullable
  private Boolean archived;

  public static final String JSON_PROPERTY_FORKABLE = "forkable";
  @jakarta.annotation.Nullable
  private Boolean forkable;

  public static final String JSON_PROPERTY_DEFAULT_BRANCH = "defaultBranch";
  @jakarta.annotation.Nullable
  private String defaultBranch;

  public static final String JSON_PROPERTY_PARTITION = "partition";
  @jakarta.annotation.Nullable
  private Integer partition;

  public static final String JSON_PROPERTY_RELATED_LINKS = "relatedLinks";
  @jakarta.annotation.Nullable
  private Object relatedLinks;

  public static final String JSON_PROPERTY_PROJECT = "project";
  @jakarta.annotation.Nullable
  private RestPullRequestFromRefRepositoryProject project;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_SCOPE = "scope";
  @jakarta.annotation.Nullable
  private String scope;

  public static final String JSON_PROPERTY_ORIGIN = "origin";
  @jakarta.annotation.Nullable
  private RestPullRequestFromRefRepositoryOrigin origin;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  /**
   * Gets or Sets state
   */
  public enum StateEnum {
    AVAILABLE(String.valueOf("AVAILABLE")),
    
    INITIALISATION_FAILED(String.valueOf("INITIALISATION_FAILED")),
    
    INITIALISING(String.valueOf("INITIALISING")),
    
    OFFLINE(String.valueOf("OFFLINE"));

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nullable
  private StateEnum state;

  public static final String JSON_PROPERTY_PUBLIC = "public";
  @jakarta.annotation.Nullable
  private Boolean _public;

  public static final String JSON_PROPERTY_LINKS = "links";
  @jakarta.annotation.Nullable
  private Object links;

  public RestLabelable() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public RestLabelable(
    @JsonProperty(JSON_PROPERTY_HIERARCHY_ID) String hierarchyId, 
    @JsonProperty(JSON_PROPERTY_STATUS_MESSAGE) String statusMessage, 
    @JsonProperty(JSON_PROPERTY_ARCHIVED) Boolean archived, 
    @JsonProperty(JSON_PROPERTY_FORKABLE) Boolean forkable, 
    @JsonProperty(JSON_PROPERTY_DEFAULT_BRANCH) String defaultBranch, 
    @JsonProperty(JSON_PROPERTY_PARTITION) Integer partition, 
    @JsonProperty(JSON_PROPERTY_RELATED_LINKS) Object relatedLinks, 
    @JsonProperty(JSON_PROPERTY_DESCRIPTION) String description, 
    @JsonProperty(JSON_PROPERTY_SCOPE) String scope, 
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_STATE) StateEnum state, 
    @JsonProperty(JSON_PROPERTY_PUBLIC) Boolean _public
  ) {
    this();
    this.hierarchyId = hierarchyId;
    this.statusMessage = statusMessage;
    this.archived = archived;
    this.forkable = forkable;
    this.defaultBranch = defaultBranch;
    this.partition = partition;
    this.relatedLinks = relatedLinks;
    this.description = description;
    this.scope = scope;
    this.id = id;
    this.state = state;
    this._public = _public;
  }

  public RestLabelable labelableType(@jakarta.annotation.Nullable LabelableTypeEnum labelableType) {
    
    this.labelableType = labelableType;
    return this;
  }

  /**
   * Get labelableType
   * @return labelableType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LABELABLE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LabelableTypeEnum getLabelableType() {
    return labelableType;
  }


  @JsonProperty(JSON_PROPERTY_LABELABLE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabelableType(@jakarta.annotation.Nullable LabelableTypeEnum labelableType) {
    this.labelableType = labelableType;
  }

  /**
   * Get hierarchyId
   * @return hierarchyId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HIERARCHY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHierarchyId() {
    return hierarchyId;
  }



  public RestLabelable scmId(@jakarta.annotation.Nullable String scmId) {
    
    this.scmId = scmId;
    return this;
  }

  /**
   * Get scmId
   * @return scmId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScmId() {
    return scmId;
  }


  @JsonProperty(JSON_PROPERTY_SCM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScmId(@jakarta.annotation.Nullable String scmId) {
    this.scmId = scmId;
  }

  public RestLabelable slug(@jakarta.annotation.Nullable String slug) {
    
    this.slug = slug;
    return this;
  }

  /**
   * Get slug
   * @return slug
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SLUG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSlug() {
    return slug;
  }


  @JsonProperty(JSON_PROPERTY_SLUG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSlug(@jakarta.annotation.Nullable String slug) {
    this.slug = slug;
  }

  /**
   * Get statusMessage
   * @return statusMessage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatusMessage() {
    return statusMessage;
  }



  /**
   * Get archived
   * @return archived
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ARCHIVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getArchived() {
    return archived;
  }



  /**
   * Get forkable
   * @return forkable
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FORKABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getForkable() {
    return forkable;
  }



  /**
   * Get defaultBranch
   * @return defaultBranch
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT_BRANCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefaultBranch() {
    return defaultBranch;
  }



  /**
   * Get partition
   * @return partition
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARTITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPartition() {
    return partition;
  }



  /**
   * Get relatedLinks
   * @return relatedLinks
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getRelatedLinks() {
    return relatedLinks;
  }



  public RestLabelable project(@jakarta.annotation.Nullable RestPullRequestFromRefRepositoryProject project) {
    
    this.project = project;
    return this;
  }

  /**
   * Get project
   * @return project
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestPullRequestFromRefRepositoryProject getProject() {
    return project;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProject(@jakarta.annotation.Nullable RestPullRequestFromRefRepositoryProject project) {
    this.project = project;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }



  /**
   * Get scope
   * @return scope
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScope() {
    return scope;
  }



  public RestLabelable origin(@jakarta.annotation.Nullable RestPullRequestFromRefRepositoryOrigin origin) {
    
    this.origin = origin;
    return this;
  }

  /**
   * Get origin
   * @return origin
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORIGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestPullRequestFromRefRepositoryOrigin getOrigin() {
    return origin;
  }


  @JsonProperty(JSON_PROPERTY_ORIGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrigin(@jakarta.annotation.Nullable RestPullRequestFromRefRepositoryOrigin origin) {
    this.origin = origin;
  }

  public RestLabelable name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  /**
   * Get state
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StateEnum getState() {
    return state;
  }



  /**
   * Get _public
   * @return _public
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPublic() {
    return _public;
  }



  public RestLabelable links(@jakarta.annotation.Nullable Object links) {
    
    this.links = links;
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(@jakarta.annotation.Nullable Object links) {
    this.links = links;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestLabelable restLabelable = (RestLabelable) o;
    return Objects.equals(this.labelableType, restLabelable.labelableType) &&
        Objects.equals(this.hierarchyId, restLabelable.hierarchyId) &&
        Objects.equals(this.scmId, restLabelable.scmId) &&
        Objects.equals(this.slug, restLabelable.slug) &&
        Objects.equals(this.statusMessage, restLabelable.statusMessage) &&
        Objects.equals(this.archived, restLabelable.archived) &&
        Objects.equals(this.forkable, restLabelable.forkable) &&
        Objects.equals(this.defaultBranch, restLabelable.defaultBranch) &&
        Objects.equals(this.partition, restLabelable.partition) &&
        Objects.equals(this.relatedLinks, restLabelable.relatedLinks) &&
        Objects.equals(this.project, restLabelable.project) &&
        Objects.equals(this.description, restLabelable.description) &&
        Objects.equals(this.scope, restLabelable.scope) &&
        Objects.equals(this.origin, restLabelable.origin) &&
        Objects.equals(this.name, restLabelable.name) &&
        Objects.equals(this.id, restLabelable.id) &&
        Objects.equals(this.state, restLabelable.state) &&
        Objects.equals(this._public, restLabelable._public) &&
        Objects.equals(this.links, restLabelable.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labelableType, hierarchyId, scmId, slug, statusMessage, archived, forkable, defaultBranch, partition, relatedLinks, project, description, scope, origin, name, id, state, _public, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestLabelable {\n");
    sb.append("    labelableType: ").append(toIndentedString(labelableType)).append("\n");
    sb.append("    hierarchyId: ").append(toIndentedString(hierarchyId)).append("\n");
    sb.append("    scmId: ").append(toIndentedString(scmId)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    statusMessage: ").append(toIndentedString(statusMessage)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    forkable: ").append(toIndentedString(forkable)).append("\n");
    sb.append("    defaultBranch: ").append(toIndentedString(defaultBranch)).append("\n");
    sb.append("    partition: ").append(toIndentedString(partition)).append("\n");
    sb.append("    relatedLinks: ").append(toIndentedString(relatedLinks)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    _public: ").append(toIndentedString(_public)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

