/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestDetailedInvocationEventScope;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestDetailedInvocation
 */
@JsonPropertyOrder({
  RestDetailedInvocation.JSON_PROPERTY_EVENT_SCOPE,
  RestDetailedInvocation.JSON_PROPERTY_FINISH,
  RestDetailedInvocation.JSON_PROPERTY_EVENT,
  RestDetailedInvocation.JSON_PROPERTY_START,
  RestDetailedInvocation.JSON_PROPERTY_REQUEST,
  RestDetailedInvocation.JSON_PROPERTY_DURATION,
  RestDetailedInvocation.JSON_PROPERTY_ID,
  RestDetailedInvocation.JSON_PROPERTY_RESULT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestDetailedInvocation implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_EVENT_SCOPE = "eventScope";
  @jakarta.annotation.Nullable
  private RestDetailedInvocationEventScope eventScope;

  public static final String JSON_PROPERTY_FINISH = "finish";
  @jakarta.annotation.Nullable
  private Integer finish;

  public static final String JSON_PROPERTY_EVENT = "event";
  @jakarta.annotation.Nullable
  private String event;

  public static final String JSON_PROPERTY_START = "start";
  @jakarta.annotation.Nullable
  private Integer start;

  public static final String JSON_PROPERTY_REQUEST = "request";
  @jakarta.annotation.Nullable
  private Object request;

  public static final String JSON_PROPERTY_DURATION = "duration";
  @jakarta.annotation.Nullable
  private Integer duration;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_RESULT = "result";
  @jakarta.annotation.Nullable
  private Object result;

  public RestDetailedInvocation() {
  }

  public RestDetailedInvocation eventScope(@jakarta.annotation.Nullable RestDetailedInvocationEventScope eventScope) {
    
    this.eventScope = eventScope;
    return this;
  }

  /**
   * Get eventScope
   * @return eventScope
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestDetailedInvocationEventScope getEventScope() {
    return eventScope;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventScope(@jakarta.annotation.Nullable RestDetailedInvocationEventScope eventScope) {
    this.eventScope = eventScope;
  }

  public RestDetailedInvocation finish(@jakarta.annotation.Nullable Integer finish) {
    
    this.finish = finish;
    return this;
  }

  /**
   * Get finish
   * @return finish
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINISH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFinish() {
    return finish;
  }


  @JsonProperty(JSON_PROPERTY_FINISH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinish(@jakarta.annotation.Nullable Integer finish) {
    this.finish = finish;
  }

  public RestDetailedInvocation event(@jakarta.annotation.Nullable String event) {
    
    this.event = event;
    return this;
  }

  /**
   * Get event
   * @return event
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEvent() {
    return event;
  }


  @JsonProperty(JSON_PROPERTY_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvent(@jakarta.annotation.Nullable String event) {
    this.event = event;
  }

  public RestDetailedInvocation start(@jakarta.annotation.Nullable Integer start) {
    
    this.start = start;
    return this;
  }

  /**
   * Get start
   * @return start
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStart() {
    return start;
  }


  @JsonProperty(JSON_PROPERTY_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStart(@jakarta.annotation.Nullable Integer start) {
    this.start = start;
  }

  public RestDetailedInvocation request(@jakarta.annotation.Nullable Object request) {
    
    this.request = request;
    return this;
  }

  /**
   * Get request
   * @return request
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getRequest() {
    return request;
  }


  @JsonProperty(JSON_PROPERTY_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequest(@jakarta.annotation.Nullable Object request) {
    this.request = request;
  }

  public RestDetailedInvocation duration(@jakarta.annotation.Nullable Integer duration) {
    
    this.duration = duration;
    return this;
  }

  /**
   * Get duration
   * @return duration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDuration() {
    return duration;
  }


  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(@jakarta.annotation.Nullable Integer duration) {
    this.duration = duration;
  }

  public RestDetailedInvocation id(@jakarta.annotation.Nullable Integer id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
  }

  public RestDetailedInvocation result(@jakarta.annotation.Nullable Object result) {
    
    this.result = result;
    return this;
  }

  /**
   * Get result
   * @return result
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getResult() {
    return result;
  }


  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResult(@jakarta.annotation.Nullable Object result) {
    this.result = result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestDetailedInvocation restDetailedInvocation = (RestDetailedInvocation) o;
    return Objects.equals(this.eventScope, restDetailedInvocation.eventScope) &&
        Objects.equals(this.finish, restDetailedInvocation.finish) &&
        Objects.equals(this.event, restDetailedInvocation.event) &&
        Objects.equals(this.start, restDetailedInvocation.start) &&
        Objects.equals(this.request, restDetailedInvocation.request) &&
        Objects.equals(this.duration, restDetailedInvocation.duration) &&
        Objects.equals(this.id, restDetailedInvocation.id) &&
        Objects.equals(this.result, restDetailedInvocation.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventScope, finish, event, start, request, duration, id, result);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestDetailedInvocation {\n");
    sb.append("    eventScope: ").append(toIndentedString(eventScope)).append("\n");
    sb.append("    finish: ").append(toIndentedString(finish)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

