/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestBulkUserRateLimitSettingsUpdateRequestSettings
 */
@JsonPropertyOrder({
  RestBulkUserRateLimitSettingsUpdateRequestSettings.JSON_PROPERTY_CAPACITY,
  RestBulkUserRateLimitSettingsUpdateRequestSettings.JSON_PROPERTY_FILL_RATE
})
@JsonTypeName("RestBulkUserRateLimitSettingsUpdateRequest_settings")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestBulkUserRateLimitSettingsUpdateRequestSettings implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CAPACITY = "capacity";
  @jakarta.annotation.Nullable
  private Integer capacity;

  public static final String JSON_PROPERTY_FILL_RATE = "fillRate";
  @jakarta.annotation.Nullable
  private Integer fillRate;

  public RestBulkUserRateLimitSettingsUpdateRequestSettings() {
  }

  public RestBulkUserRateLimitSettingsUpdateRequestSettings capacity(@jakarta.annotation.Nullable Integer capacity) {
    
    this.capacity = capacity;
    return this;
  }

  /**
   * Get capacity
   * @return capacity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCapacity() {
    return capacity;
  }


  @JsonProperty(JSON_PROPERTY_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCapacity(@jakarta.annotation.Nullable Integer capacity) {
    this.capacity = capacity;
  }

  public RestBulkUserRateLimitSettingsUpdateRequestSettings fillRate(@jakarta.annotation.Nullable Integer fillRate) {
    
    this.fillRate = fillRate;
    return this;
  }

  /**
   * Get fillRate
   * @return fillRate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILL_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFillRate() {
    return fillRate;
  }


  @JsonProperty(JSON_PROPERTY_FILL_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFillRate(@jakarta.annotation.Nullable Integer fillRate) {
    this.fillRate = fillRate;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestBulkUserRateLimitSettingsUpdateRequestSettings restBulkUserRateLimitSettingsUpdateRequestSettings = (RestBulkUserRateLimitSettingsUpdateRequestSettings) o;
    return Objects.equals(this.capacity, restBulkUserRateLimitSettingsUpdateRequestSettings.capacity) &&
        Objects.equals(this.fillRate, restBulkUserRateLimitSettingsUpdateRequestSettings.fillRate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(capacity, fillRate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestBulkUserRateLimitSettingsUpdateRequestSettings {\n");
    sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
    sb.append("    fillRate: ").append(toIndentedString(fillRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

