/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestSshKeyTypeRestrictionMinKeyLength;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestSshKeyTypeRestriction
 */
@JsonPropertyOrder({
  RestSshKeyTypeRestriction.JSON_PROPERTY_MIN_KEY_LENGTH,
  RestSshKeyTypeRestriction.JSON_PROPERTY_ALGORITHM,
  RestSshKeyTypeRestriction.JSON_PROPERTY_ALLOWED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestSshKeyTypeRestriction implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_MIN_KEY_LENGTH = "minKeyLength";
  @jakarta.annotation.Nullable
  private RestSshKeyTypeRestrictionMinKeyLength minKeyLength;

  public static final String JSON_PROPERTY_ALGORITHM = "algorithm";
  @jakarta.annotation.Nullable
  private String algorithm;

  public static final String JSON_PROPERTY_ALLOWED = "allowed";
  @jakarta.annotation.Nullable
  private Boolean allowed;

  public RestSshKeyTypeRestriction() {
  }

  public RestSshKeyTypeRestriction minKeyLength(@jakarta.annotation.Nullable RestSshKeyTypeRestrictionMinKeyLength minKeyLength) {
    
    this.minKeyLength = minKeyLength;
    return this;
  }

  /**
   * Get minKeyLength
   * @return minKeyLength
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MIN_KEY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestSshKeyTypeRestrictionMinKeyLength getMinKeyLength() {
    return minKeyLength;
  }


  @JsonProperty(JSON_PROPERTY_MIN_KEY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinKeyLength(@jakarta.annotation.Nullable RestSshKeyTypeRestrictionMinKeyLength minKeyLength) {
    this.minKeyLength = minKeyLength;
  }

  public RestSshKeyTypeRestriction algorithm(@jakarta.annotation.Nullable String algorithm) {
    
    this.algorithm = algorithm;
    return this;
  }

  /**
   * Get algorithm
   * @return algorithm
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAlgorithm() {
    return algorithm;
  }


  @JsonProperty(JSON_PROPERTY_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlgorithm(@jakarta.annotation.Nullable String algorithm) {
    this.algorithm = algorithm;
  }

  public RestSshKeyTypeRestriction allowed(@jakarta.annotation.Nullable Boolean allowed) {
    
    this.allowed = allowed;
    return this;
  }

  /**
   * Get allowed
   * @return allowed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALLOWED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAllowed() {
    return allowed;
  }


  @JsonProperty(JSON_PROPERTY_ALLOWED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowed(@jakarta.annotation.Nullable Boolean allowed) {
    this.allowed = allowed;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestSshKeyTypeRestriction restSshKeyTypeRestriction = (RestSshKeyTypeRestriction) o;
    return Objects.equals(this.minKeyLength, restSshKeyTypeRestriction.minKeyLength) &&
        Objects.equals(this.algorithm, restSshKeyTypeRestriction.algorithm) &&
        Objects.equals(this.allowed, restSshKeyTypeRestriction.allowed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minKeyLength, algorithm, allowed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestSshKeyTypeRestriction {\n");
    sb.append("    minKeyLength: ").append(toIndentedString(minKeyLength)).append("\n");
    sb.append("    algorithm: ").append(toIndentedString(algorithm)).append("\n");
    sb.append("    allowed: ").append(toIndentedString(allowed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

