/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestApplicationUser;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestDefaultReviewersRequestSourceMatcher;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestPullRequestConditionScope;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestSshAccessKey;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestRestrictionRequest
 */
@JsonPropertyOrder({
  RestRestrictionRequest.JSON_PROPERTY_ACCESS_KEY_IDS,
  RestRestrictionRequest.JSON_PROPERTY_ACCESS_KEYS,
  RestRestrictionRequest.JSON_PROPERTY_GROUP_NAMES,
  RestRestrictionRequest.JSON_PROPERTY_GROUPS,
  RestRestrictionRequest.JSON_PROPERTY_ID,
  RestRestrictionRequest.JSON_PROPERTY_MATCHER,
  RestRestrictionRequest.JSON_PROPERTY_SCOPE,
  RestRestrictionRequest.JSON_PROPERTY_TYPE,
  RestRestrictionRequest.JSON_PROPERTY_USER_SLUGS,
  RestRestrictionRequest.JSON_PROPERTY_USERS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestRestrictionRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ACCESS_KEY_IDS = "accessKeyIds";
  @jakarta.annotation.Nullable
  private List<Integer> accessKeyIds = new ArrayList<>();

  public static final String JSON_PROPERTY_ACCESS_KEYS = "accessKeys";
  @jakarta.annotation.Nullable
  private List<RestSshAccessKey> accessKeys = new ArrayList<>();

  public static final String JSON_PROPERTY_GROUP_NAMES = "groupNames";
  @jakarta.annotation.Nullable
  private List<String> groupNames = new ArrayList<>();

  public static final String JSON_PROPERTY_GROUPS = "groups";
  @jakarta.annotation.Nullable
  private List<String> groups = new ArrayList<>();

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_MATCHER = "matcher";
  @jakarta.annotation.Nullable
  private RestDefaultReviewersRequestSourceMatcher matcher;

  public static final String JSON_PROPERTY_SCOPE = "scope";
  @jakarta.annotation.Nullable
  private RestPullRequestConditionScope scope;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_USER_SLUGS = "userSlugs";
  @jakarta.annotation.Nullable
  private List<String> userSlugs = new ArrayList<>();

  public static final String JSON_PROPERTY_USERS = "users";
  @jakarta.annotation.Nullable
  private List<RestApplicationUser> users = new ArrayList<>();

  public RestRestrictionRequest() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public RestRestrictionRequest(
    @JsonProperty(JSON_PROPERTY_ID) Integer id
  ) {
    this();
    this.id = id;
  }

  public RestRestrictionRequest accessKeyIds(@jakarta.annotation.Nullable List<Integer> accessKeyIds) {
    
    this.accessKeyIds = accessKeyIds;
    return this;
  }

  public RestRestrictionRequest addAccessKeyIdsItem(Integer accessKeyIdsItem) {
    if (this.accessKeyIds == null) {
      this.accessKeyIds = new ArrayList<>();
    }
    this.accessKeyIds.add(accessKeyIdsItem);
    return this;
  }

  /**
   * Get accessKeyIds
   * @return accessKeyIds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_KEY_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getAccessKeyIds() {
    return accessKeyIds;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_KEY_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessKeyIds(@jakarta.annotation.Nullable List<Integer> accessKeyIds) {
    this.accessKeyIds = accessKeyIds;
  }

  public RestRestrictionRequest accessKeys(@jakarta.annotation.Nullable List<RestSshAccessKey> accessKeys) {
    
    this.accessKeys = accessKeys;
    return this;
  }

  public RestRestrictionRequest addAccessKeysItem(RestSshAccessKey accessKeysItem) {
    if (this.accessKeys == null) {
      this.accessKeys = new ArrayList<>();
    }
    this.accessKeys.add(accessKeysItem);
    return this;
  }

  /**
   * Get accessKeys
   * @return accessKeys
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RestSshAccessKey> getAccessKeys() {
    return accessKeys;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessKeys(@jakarta.annotation.Nullable List<RestSshAccessKey> accessKeys) {
    this.accessKeys = accessKeys;
  }

  public RestRestrictionRequest groupNames(@jakarta.annotation.Nullable List<String> groupNames) {
    
    this.groupNames = groupNames;
    return this;
  }

  public RestRestrictionRequest addGroupNamesItem(String groupNamesItem) {
    if (this.groupNames == null) {
      this.groupNames = new ArrayList<>();
    }
    this.groupNames.add(groupNamesItem);
    return this;
  }

  /**
   * Get groupNames
   * @return groupNames
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getGroupNames() {
    return groupNames;
  }


  @JsonProperty(JSON_PROPERTY_GROUP_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupNames(@jakarta.annotation.Nullable List<String> groupNames) {
    this.groupNames = groupNames;
  }

  public RestRestrictionRequest groups(@jakarta.annotation.Nullable List<String> groups) {
    
    this.groups = groups;
    return this;
  }

  public RestRestrictionRequest addGroupsItem(String groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

  /**
   * Get groups
   * @return groups
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getGroups() {
    return groups;
  }


  @JsonProperty(JSON_PROPERTY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroups(@jakarta.annotation.Nullable List<String> groups) {
    this.groups = groups;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  public RestRestrictionRequest matcher(@jakarta.annotation.Nullable RestDefaultReviewersRequestSourceMatcher matcher) {
    
    this.matcher = matcher;
    return this;
  }

  /**
   * Get matcher
   * @return matcher
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATCHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestDefaultReviewersRequestSourceMatcher getMatcher() {
    return matcher;
  }


  @JsonProperty(JSON_PROPERTY_MATCHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMatcher(@jakarta.annotation.Nullable RestDefaultReviewersRequestSourceMatcher matcher) {
    this.matcher = matcher;
  }

  public RestRestrictionRequest scope(@jakarta.annotation.Nullable RestPullRequestConditionScope scope) {
    
    this.scope = scope;
    return this;
  }

  /**
   * Get scope
   * @return scope
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestPullRequestConditionScope getScope() {
    return scope;
  }


  @JsonProperty(JSON_PROPERTY_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScope(@jakarta.annotation.Nullable RestPullRequestConditionScope scope) {
    this.scope = scope;
  }

  public RestRestrictionRequest type(@jakarta.annotation.Nullable String type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable String type) {
    this.type = type;
  }

  public RestRestrictionRequest userSlugs(@jakarta.annotation.Nullable List<String> userSlugs) {
    
    this.userSlugs = userSlugs;
    return this;
  }

  public RestRestrictionRequest addUserSlugsItem(String userSlugsItem) {
    if (this.userSlugs == null) {
      this.userSlugs = new ArrayList<>();
    }
    this.userSlugs.add(userSlugsItem);
    return this;
  }

  /**
   * Get userSlugs
   * @return userSlugs
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_SLUGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getUserSlugs() {
    return userSlugs;
  }


  @JsonProperty(JSON_PROPERTY_USER_SLUGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserSlugs(@jakarta.annotation.Nullable List<String> userSlugs) {
    this.userSlugs = userSlugs;
  }

  public RestRestrictionRequest users(@jakarta.annotation.Nullable List<RestApplicationUser> users) {
    
    this.users = users;
    return this;
  }

  public RestRestrictionRequest addUsersItem(RestApplicationUser usersItem) {
    if (this.users == null) {
      this.users = new ArrayList<>();
    }
    this.users.add(usersItem);
    return this;
  }

  /**
   * Get users
   * @return users
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RestApplicationUser> getUsers() {
    return users;
  }


  @JsonProperty(JSON_PROPERTY_USERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsers(@jakarta.annotation.Nullable List<RestApplicationUser> users) {
    this.users = users;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestRestrictionRequest restRestrictionRequest = (RestRestrictionRequest) o;
    return Objects.equals(this.accessKeyIds, restRestrictionRequest.accessKeyIds) &&
        Objects.equals(this.accessKeys, restRestrictionRequest.accessKeys) &&
        Objects.equals(this.groupNames, restRestrictionRequest.groupNames) &&
        Objects.equals(this.groups, restRestrictionRequest.groups) &&
        Objects.equals(this.id, restRestrictionRequest.id) &&
        Objects.equals(this.matcher, restRestrictionRequest.matcher) &&
        Objects.equals(this.scope, restRestrictionRequest.scope) &&
        Objects.equals(this.type, restRestrictionRequest.type) &&
        Objects.equals(this.userSlugs, restRestrictionRequest.userSlugs) &&
        Objects.equals(this.users, restRestrictionRequest.users);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessKeyIds, accessKeys, groupNames, groups, id, matcher, scope, type, userSlugs, users);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestRestrictionRequest {\n");
    sb.append("    accessKeyIds: ").append(toIndentedString(accessKeyIds)).append("\n");
    sb.append("    accessKeys: ").append(toIndentedString(accessKeys)).append("\n");
    sb.append("    groupNames: ").append(toIndentedString(groupNames)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    matcher: ").append(toIndentedString(matcher)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    userSlugs: ").append(toIndentedString(userSlugs)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

