/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestPullRequestFromRefRepository;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestMigrationRepository
 */
@JsonPropertyOrder({
  RestMigrationRepository.JSON_PROPERTY_MIGRATION_STATE,
  RestMigrationRepository.JSON_PROPERTY_REPOSITORY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestMigrationRepository implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * Gets or Sets migrationState
   */
  public enum MigrationStateEnum {
    QUEUED(String.valueOf("QUEUED")),
    
    STAGING(String.valueOf("STAGING")),
    
    STAGED(String.valueOf("STAGED")),
    
    MIGRATED(String.valueOf("MIGRATED")),
    
    FAILED(String.valueOf("FAILED")),
    
    CANCELED(String.valueOf("CANCELED")),
    
    SKIPPED(String.valueOf("SKIPPED"));

    private String value;

    MigrationStateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MigrationStateEnum fromValue(String value) {
      for (MigrationStateEnum b : MigrationStateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MIGRATION_STATE = "migrationState";
  @jakarta.annotation.Nullable
  private MigrationStateEnum migrationState;

  public static final String JSON_PROPERTY_REPOSITORY = "repository";
  @jakarta.annotation.Nullable
  private RestPullRequestFromRefRepository repository;

  public RestMigrationRepository() {
  }

  public RestMigrationRepository migrationState(@jakarta.annotation.Nullable MigrationStateEnum migrationState) {
    
    this.migrationState = migrationState;
    return this;
  }

  /**
   * Get migrationState
   * @return migrationState
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MIGRATION_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MigrationStateEnum getMigrationState() {
    return migrationState;
  }


  @JsonProperty(JSON_PROPERTY_MIGRATION_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMigrationState(@jakarta.annotation.Nullable MigrationStateEnum migrationState) {
    this.migrationState = migrationState;
  }

  public RestMigrationRepository repository(@jakarta.annotation.Nullable RestPullRequestFromRefRepository repository) {
    
    this.repository = repository;
    return this;
  }

  /**
   * Get repository
   * @return repository
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPOSITORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestPullRequestFromRefRepository getRepository() {
    return repository;
  }


  @JsonProperty(JSON_PROPERTY_REPOSITORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepository(@jakarta.annotation.Nullable RestPullRequestFromRefRepository repository) {
    this.repository = repository;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestMigrationRepository restMigrationRepository = (RestMigrationRepository) o;
    return Objects.equals(this.migrationState, restMigrationRepository.migrationState) &&
        Objects.equals(this.repository, restMigrationRepository.repository);
  }

  @Override
  public int hashCode() {
    return Objects.hash(migrationState, repository);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestMigrationRepository {\n");
    sb.append("    migrationState: ").append(toIndentedString(migrationState)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

