/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestPullRequestRebaseResultRefChangeRef;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestRefChange
 */
@JsonPropertyOrder({
  RestRefChange.JSON_PROPERTY_FROM_HASH,
  RestRefChange.JSON_PROPERTY_TO_HASH,
  RestRefChange.JSON_PROPERTY_REF_ID,
  RestRefChange.JSON_PROPERTY_TYPE,
  RestRefChange.JSON_PROPERTY_REF
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T09:35:07.114611322+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class RestRefChange implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_FROM_HASH = "fromHash";
  @jakarta.annotation.Nullable
  private String fromHash;

  public static final String JSON_PROPERTY_TO_HASH = "toHash";
  @jakarta.annotation.Nullable
  private String toHash;

  public static final String JSON_PROPERTY_REF_ID = "refId";
  @jakarta.annotation.Nullable
  private String refId;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    ADD(String.valueOf("ADD")),
    
    DELETE(String.valueOf("DELETE")),
    
    UPDATE(String.valueOf("UPDATE"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type;

  public static final String JSON_PROPERTY_REF = "ref";
  @jakarta.annotation.Nullable
  private RestPullRequestRebaseResultRefChangeRef ref;

  public RestRefChange() {
  }

  public RestRefChange fromHash(@jakarta.annotation.Nullable String fromHash) {
    
    this.fromHash = fromHash;
    return this;
  }

  /**
   * Get fromHash
   * @return fromHash
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FROM_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFromHash() {
    return fromHash;
  }


  @JsonProperty(JSON_PROPERTY_FROM_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromHash(@jakarta.annotation.Nullable String fromHash) {
    this.fromHash = fromHash;
  }

  public RestRefChange toHash(@jakarta.annotation.Nullable String toHash) {
    
    this.toHash = toHash;
    return this;
  }

  /**
   * Get toHash
   * @return toHash
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TO_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToHash() {
    return toHash;
  }


  @JsonProperty(JSON_PROPERTY_TO_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToHash(@jakarta.annotation.Nullable String toHash) {
    this.toHash = toHash;
  }

  public RestRefChange refId(@jakarta.annotation.Nullable String refId) {
    
    this.refId = refId;
    return this;
  }

  /**
   * Get refId
   * @return refId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REF_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRefId() {
    return refId;
  }


  @JsonProperty(JSON_PROPERTY_REF_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefId(@jakarta.annotation.Nullable String refId) {
    this.refId = refId;
  }

  public RestRefChange type(@jakarta.annotation.Nullable TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
  }

  public RestRefChange ref(@jakarta.annotation.Nullable RestPullRequestRebaseResultRefChangeRef ref) {
    
    this.ref = ref;
    return this;
  }

  /**
   * Get ref
   * @return ref
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestPullRequestRebaseResultRefChangeRef getRef() {
    return ref;
  }


  @JsonProperty(JSON_PROPERTY_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRef(@jakarta.annotation.Nullable RestPullRequestRebaseResultRefChangeRef ref) {
    this.ref = ref;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestRefChange restRefChange = (RestRefChange) o;
    return Objects.equals(this.fromHash, restRefChange.fromHash) &&
        Objects.equals(this.toHash, restRefChange.toHash) &&
        Objects.equals(this.refId, restRefChange.refId) &&
        Objects.equals(this.type, restRefChange.type) &&
        Objects.equals(this.ref, restRefChange.ref);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromHash, toHash, refId, type, ref);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestRefChange {\n");
    sb.append("    fromHash: ").append(toIndentedString(fromHash)).append("\n");
    sb.append("    toHash: ").append(toIndentedString(toHash)).append("\n");
    sb.append("    refId: ").append(toIndentedString(refId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

