/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestPullRequestFromRef;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestPullRequestParticipant;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestCommentThreadDiffAnchorPullRequest
 */
@JsonPropertyOrder({
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_UPDATED_DATE,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_CREATED_DATE,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_FROM_REF,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_PARTICIPANTS,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_REVIEWERS,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_TO_REF,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_HTML_DESCRIPTION,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_CLOSED_DATE,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_VERSION,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_LOCKED,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_DESCRIPTION,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_CLOSED,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_TITLE,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_ID,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_STATE,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_OPEN,
  RestCommentThreadDiffAnchorPullRequest.JSON_PROPERTY_LINKS
})
@JsonTypeName("RestCommentThreadDiffAnchor_pullRequest")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-28T09:35:07.114611322+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class RestCommentThreadDiffAnchorPullRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_UPDATED_DATE = "updatedDate";
  @jakarta.annotation.Nullable
  private Long updatedDate;

  public static final String JSON_PROPERTY_CREATED_DATE = "createdDate";
  @jakarta.annotation.Nullable
  private Long createdDate;

  public static final String JSON_PROPERTY_FROM_REF = "fromRef";
  @jakarta.annotation.Nullable
  private RestPullRequestFromRef fromRef;

  public static final String JSON_PROPERTY_PARTICIPANTS = "participants";
  @jakarta.annotation.Nullable
  private List<RestPullRequestParticipant> participants = new ArrayList<>();

  public static final String JSON_PROPERTY_REVIEWERS = "reviewers";
  @jakarta.annotation.Nullable
  private List<RestPullRequestParticipant> reviewers = new ArrayList<>();

  public static final String JSON_PROPERTY_TO_REF = "toRef";
  @jakarta.annotation.Nullable
  private RestPullRequestFromRef toRef;

  public static final String JSON_PROPERTY_HTML_DESCRIPTION = "htmlDescription";
  @jakarta.annotation.Nullable
  private String htmlDescription;

  public static final String JSON_PROPERTY_CLOSED_DATE = "closedDate";
  @jakarta.annotation.Nullable
  private Long closedDate;

  public static final String JSON_PROPERTY_VERSION = "version";
  @jakarta.annotation.Nullable
  private Integer version;

  public static final String JSON_PROPERTY_LOCKED = "locked";
  @jakarta.annotation.Nullable
  private Boolean locked;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_CLOSED = "closed";
  @jakarta.annotation.Nullable
  private Boolean closed;

  public static final String JSON_PROPERTY_TITLE = "title";
  @jakarta.annotation.Nullable
  private String title;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  /**
   * Gets or Sets state
   */
  public enum StateEnum {
    DECLINED(String.valueOf("DECLINED")),
    
    MERGED(String.valueOf("MERGED")),
    
    OPEN(String.valueOf("OPEN"));

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nullable
  private StateEnum state;

  public static final String JSON_PROPERTY_OPEN = "open";
  @jakarta.annotation.Nullable
  private Boolean open;

  public static final String JSON_PROPERTY_LINKS = "links";
  @jakarta.annotation.Nullable
  private Object links;

  public RestCommentThreadDiffAnchorPullRequest() {
  }

  public RestCommentThreadDiffAnchorPullRequest updatedDate(@jakarta.annotation.Nullable Long updatedDate) {
    
    this.updatedDate = updatedDate;
    return this;
  }

  /**
   * Get updatedDate
   * @return updatedDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUpdatedDate() {
    return updatedDate;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedDate(@jakarta.annotation.Nullable Long updatedDate) {
    this.updatedDate = updatedDate;
  }

  public RestCommentThreadDiffAnchorPullRequest createdDate(@jakarta.annotation.Nullable Long createdDate) {
    
    this.createdDate = createdDate;
    return this;
  }

  /**
   * Get createdDate
   * @return createdDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCreatedDate() {
    return createdDate;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedDate(@jakarta.annotation.Nullable Long createdDate) {
    this.createdDate = createdDate;
  }

  public RestCommentThreadDiffAnchorPullRequest fromRef(@jakarta.annotation.Nullable RestPullRequestFromRef fromRef) {
    
    this.fromRef = fromRef;
    return this;
  }

  /**
   * Get fromRef
   * @return fromRef
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FROM_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestPullRequestFromRef getFromRef() {
    return fromRef;
  }


  @JsonProperty(JSON_PROPERTY_FROM_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromRef(@jakarta.annotation.Nullable RestPullRequestFromRef fromRef) {
    this.fromRef = fromRef;
  }

  public RestCommentThreadDiffAnchorPullRequest participants(@jakarta.annotation.Nullable List<RestPullRequestParticipant> participants) {
    
    this.participants = participants;
    return this;
  }

  public RestCommentThreadDiffAnchorPullRequest addParticipantsItem(RestPullRequestParticipant participantsItem) {
    if (this.participants == null) {
      this.participants = new ArrayList<>();
    }
    this.participants.add(participantsItem);
    return this;
  }

  /**
   * Get participants
   * @return participants
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARTICIPANTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RestPullRequestParticipant> getParticipants() {
    return participants;
  }


  @JsonProperty(JSON_PROPERTY_PARTICIPANTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParticipants(@jakarta.annotation.Nullable List<RestPullRequestParticipant> participants) {
    this.participants = participants;
  }

  public RestCommentThreadDiffAnchorPullRequest reviewers(@jakarta.annotation.Nullable List<RestPullRequestParticipant> reviewers) {
    
    this.reviewers = reviewers;
    return this;
  }

  public RestCommentThreadDiffAnchorPullRequest addReviewersItem(RestPullRequestParticipant reviewersItem) {
    if (this.reviewers == null) {
      this.reviewers = new ArrayList<>();
    }
    this.reviewers.add(reviewersItem);
    return this;
  }

  /**
   * Get reviewers
   * @return reviewers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REVIEWERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RestPullRequestParticipant> getReviewers() {
    return reviewers;
  }


  @JsonProperty(JSON_PROPERTY_REVIEWERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReviewers(@jakarta.annotation.Nullable List<RestPullRequestParticipant> reviewers) {
    this.reviewers = reviewers;
  }

  public RestCommentThreadDiffAnchorPullRequest toRef(@jakarta.annotation.Nullable RestPullRequestFromRef toRef) {
    
    this.toRef = toRef;
    return this;
  }

  /**
   * Get toRef
   * @return toRef
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TO_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestPullRequestFromRef getToRef() {
    return toRef;
  }


  @JsonProperty(JSON_PROPERTY_TO_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToRef(@jakarta.annotation.Nullable RestPullRequestFromRef toRef) {
    this.toRef = toRef;
  }

  public RestCommentThreadDiffAnchorPullRequest htmlDescription(@jakarta.annotation.Nullable String htmlDescription) {
    
    this.htmlDescription = htmlDescription;
    return this;
  }

  /**
   * Get htmlDescription
   * @return htmlDescription
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HTML_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHtmlDescription() {
    return htmlDescription;
  }


  @JsonProperty(JSON_PROPERTY_HTML_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHtmlDescription(@jakarta.annotation.Nullable String htmlDescription) {
    this.htmlDescription = htmlDescription;
  }

  public RestCommentThreadDiffAnchorPullRequest closedDate(@jakarta.annotation.Nullable Long closedDate) {
    
    this.closedDate = closedDate;
    return this;
  }

  /**
   * Get closedDate
   * @return closedDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLOSED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getClosedDate() {
    return closedDate;
  }


  @JsonProperty(JSON_PROPERTY_CLOSED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClosedDate(@jakarta.annotation.Nullable Long closedDate) {
    this.closedDate = closedDate;
  }

  public RestCommentThreadDiffAnchorPullRequest version(@jakarta.annotation.Nullable Integer version) {
    
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(@jakarta.annotation.Nullable Integer version) {
    this.version = version;
  }

  public RestCommentThreadDiffAnchorPullRequest locked(@jakarta.annotation.Nullable Boolean locked) {
    
    this.locked = locked;
    return this;
  }

  /**
   * Get locked
   * @return locked
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLocked() {
    return locked;
  }


  @JsonProperty(JSON_PROPERTY_LOCKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocked(@jakarta.annotation.Nullable Boolean locked) {
    this.locked = locked;
  }

  public RestCommentThreadDiffAnchorPullRequest description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public RestCommentThreadDiffAnchorPullRequest closed(@jakarta.annotation.Nullable Boolean closed) {
    
    this.closed = closed;
    return this;
  }

  /**
   * Get closed
   * @return closed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLOSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getClosed() {
    return closed;
  }


  @JsonProperty(JSON_PROPERTY_CLOSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClosed(@jakarta.annotation.Nullable Boolean closed) {
    this.closed = closed;
  }

  public RestCommentThreadDiffAnchorPullRequest title(@jakarta.annotation.Nullable String title) {
    
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@jakarta.annotation.Nullable String title) {
    this.title = title;
  }

  public RestCommentThreadDiffAnchorPullRequest id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public RestCommentThreadDiffAnchorPullRequest state(@jakarta.annotation.Nullable StateEnum state) {
    
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StateEnum getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@jakarta.annotation.Nullable StateEnum state) {
    this.state = state;
  }

  public RestCommentThreadDiffAnchorPullRequest open(@jakarta.annotation.Nullable Boolean open) {
    
    this.open = open;
    return this;
  }

  /**
   * Get open
   * @return open
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOpen() {
    return open;
  }


  @JsonProperty(JSON_PROPERTY_OPEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpen(@jakarta.annotation.Nullable Boolean open) {
    this.open = open;
  }

  public RestCommentThreadDiffAnchorPullRequest links(@jakarta.annotation.Nullable Object links) {
    
    this.links = links;
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(@jakarta.annotation.Nullable Object links) {
    this.links = links;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestCommentThreadDiffAnchorPullRequest restCommentThreadDiffAnchorPullRequest = (RestCommentThreadDiffAnchorPullRequest) o;
    return Objects.equals(this.updatedDate, restCommentThreadDiffAnchorPullRequest.updatedDate) &&
        Objects.equals(this.createdDate, restCommentThreadDiffAnchorPullRequest.createdDate) &&
        Objects.equals(this.fromRef, restCommentThreadDiffAnchorPullRequest.fromRef) &&
        Objects.equals(this.participants, restCommentThreadDiffAnchorPullRequest.participants) &&
        Objects.equals(this.reviewers, restCommentThreadDiffAnchorPullRequest.reviewers) &&
        Objects.equals(this.toRef, restCommentThreadDiffAnchorPullRequest.toRef) &&
        Objects.equals(this.htmlDescription, restCommentThreadDiffAnchorPullRequest.htmlDescription) &&
        Objects.equals(this.closedDate, restCommentThreadDiffAnchorPullRequest.closedDate) &&
        Objects.equals(this.version, restCommentThreadDiffAnchorPullRequest.version) &&
        Objects.equals(this.locked, restCommentThreadDiffAnchorPullRequest.locked) &&
        Objects.equals(this.description, restCommentThreadDiffAnchorPullRequest.description) &&
        Objects.equals(this.closed, restCommentThreadDiffAnchorPullRequest.closed) &&
        Objects.equals(this.title, restCommentThreadDiffAnchorPullRequest.title) &&
        Objects.equals(this.id, restCommentThreadDiffAnchorPullRequest.id) &&
        Objects.equals(this.state, restCommentThreadDiffAnchorPullRequest.state) &&
        Objects.equals(this.open, restCommentThreadDiffAnchorPullRequest.open) &&
        Objects.equals(this.links, restCommentThreadDiffAnchorPullRequest.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(updatedDate, createdDate, fromRef, participants, reviewers, toRef, htmlDescription, closedDate, version, locked, description, closed, title, id, state, open, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestCommentThreadDiffAnchorPullRequest {\n");
    sb.append("    updatedDate: ").append(toIndentedString(updatedDate)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    fromRef: ").append(toIndentedString(fromRef)).append("\n");
    sb.append("    participants: ").append(toIndentedString(participants)).append("\n");
    sb.append("    reviewers: ").append(toIndentedString(reviewers)).append("\n");
    sb.append("    toRef: ").append(toIndentedString(toRef)).append("\n");
    sb.append("    htmlDescription: ").append(toIndentedString(htmlDescription)).append("\n");
    sb.append("    closedDate: ").append(toIndentedString(closedDate)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    closed: ").append(toIndentedString(closed)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    open: ").append(toIndentedString(open)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

