/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestPullRequestAssignStatusRequest
 */
@JsonPropertyOrder({
  RestPullRequestAssignStatusRequest.JSON_PROPERTY_LAST_REVIEWED_COMMIT,
  RestPullRequestAssignStatusRequest.JSON_PROPERTY_STATUS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestPullRequestAssignStatusRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_LAST_REVIEWED_COMMIT = "lastReviewedCommit";
  @jakarta.annotation.Nullable
  private String lastReviewedCommit;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    UNAPPROVED(String.valueOf("UNAPPROVED")),
    
    NEEDS_WORK(String.valueOf("NEEDS_WORK")),
    
    APPROVED(String.valueOf("APPROVED"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private StatusEnum status;

  public RestPullRequestAssignStatusRequest() {
  }

  public RestPullRequestAssignStatusRequest lastReviewedCommit(@jakarta.annotation.Nullable String lastReviewedCommit) {
    
    this.lastReviewedCommit = lastReviewedCommit;
    return this;
  }

  /**
   * Get lastReviewedCommit
   * @return lastReviewedCommit
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_REVIEWED_COMMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastReviewedCommit() {
    return lastReviewedCommit;
  }


  @JsonProperty(JSON_PROPERTY_LAST_REVIEWED_COMMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastReviewedCommit(@jakarta.annotation.Nullable String lastReviewedCommit) {
    this.lastReviewedCommit = lastReviewedCommit;
  }

  public RestPullRequestAssignStatusRequest status(@jakarta.annotation.Nullable StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable StatusEnum status) {
    this.status = status;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestPullRequestAssignStatusRequest restPullRequestAssignStatusRequest = (RestPullRequestAssignStatusRequest) o;
    return Objects.equals(this.lastReviewedCommit, restPullRequestAssignStatusRequest.lastReviewedCommit) &&
        Objects.equals(this.status, restPullRequestAssignStatusRequest.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastReviewedCommit, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestPullRequestAssignStatusRequest {\n");
    sb.append("    lastReviewedCommit: ").append(toIndentedString(lastReviewedCommit)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

