/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestRepositoryPolicy
 */
@JsonPropertyOrder({
  RestRepositoryPolicy.JSON_PROPERTY_PERMISSION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestRepositoryPolicy implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * The permission required to delete repositories. Must be one of: \&quot;SYS_ADMIN\&quot;, \&quot;ADMIN\&quot;, \&quot;PROJECT_ADMIN\&quot;, \&quot;REPO_ADMIN\&quot;.
   */
  public enum PermissionEnum {
    SYS_ADMIN(String.valueOf("SYS_ADMIN")),
    
    ADMIN(String.valueOf("ADMIN")),
    
    PROJECT_ADMIN(String.valueOf("PROJECT_ADMIN")),
    
    REPO_ADMIN(String.valueOf("REPO_ADMIN"));

    private String value;

    PermissionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PermissionEnum fromValue(String value) {
      for (PermissionEnum b : PermissionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PERMISSION = "permission";
  @jakarta.annotation.Nullable
  private PermissionEnum permission;

  public RestRepositoryPolicy() {
  }

  public RestRepositoryPolicy permission(@jakarta.annotation.Nullable PermissionEnum permission) {
    
    this.permission = permission;
    return this;
  }

  /**
   * The permission required to delete repositories. Must be one of: \&quot;SYS_ADMIN\&quot;, \&quot;ADMIN\&quot;, \&quot;PROJECT_ADMIN\&quot;, \&quot;REPO_ADMIN\&quot;.
   * @return permission
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERMISSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PermissionEnum getPermission() {
    return permission;
  }


  @JsonProperty(JSON_PROPERTY_PERMISSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermission(@jakarta.annotation.Nullable PermissionEnum permission) {
    this.permission = permission;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestRepositoryPolicy restRepositoryPolicy = (RestRepositoryPolicy) o;
    return Objects.equals(this.permission, restRepositoryPolicy.permission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(permission);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestRepositoryPolicy {\n");
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

