/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.Context;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestRefSyncRequest
 */
@JsonPropertyOrder({
  RestRefSyncRequest.JSON_PROPERTY_ACTION,
  RestRefSyncRequest.JSON_PROPERTY_CONTEXT,
  RestRefSyncRequest.JSON_PROPERTY_REF_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestRefSyncRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * Gets or Sets action
   */
  public enum ActionEnum {
    DISCARD(String.valueOf("DISCARD")),
    
    MERGE(String.valueOf("MERGE")),
    
    REBASE(String.valueOf("REBASE"));

    private String value;

    ActionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActionEnum fromValue(String value) {
      for (ActionEnum b : ActionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACTION = "action";
  @jakarta.annotation.Nullable
  private ActionEnum action;

  public static final String JSON_PROPERTY_CONTEXT = "context";
  @jakarta.annotation.Nullable
  private Context context;

  public static final String JSON_PROPERTY_REF_ID = "refId";
  @jakarta.annotation.Nullable
  private String refId;

  public RestRefSyncRequest() {
  }

  public RestRefSyncRequest action(@jakarta.annotation.Nullable ActionEnum action) {
    
    this.action = action;
    return this;
  }

  /**
   * Get action
   * @return action
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActionEnum getAction() {
    return action;
  }


  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAction(@jakarta.annotation.Nullable ActionEnum action) {
    this.action = action;
  }

  public RestRefSyncRequest context(@jakarta.annotation.Nullable Context context) {
    
    this.context = context;
    return this;
  }

  /**
   * Get context
   * @return context
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Context getContext() {
    return context;
  }


  @JsonProperty(JSON_PROPERTY_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContext(@jakarta.annotation.Nullable Context context) {
    this.context = context;
  }

  public RestRefSyncRequest refId(@jakarta.annotation.Nullable String refId) {
    
    this.refId = refId;
    return this;
  }

  /**
   * Get refId
   * @return refId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REF_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRefId() {
    return refId;
  }


  @JsonProperty(JSON_PROPERTY_REF_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefId(@jakarta.annotation.Nullable String refId) {
    this.refId = refId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestRefSyncRequest restRefSyncRequest = (RestRefSyncRequest) o;
    return Objects.equals(this.action, restRefSyncRequest.action) &&
        Objects.equals(this.context, restRefSyncRequest.context) &&
        Objects.equals(this.refId, restRefSyncRequest.refId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, context, refId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestRefSyncRequest {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    refId: ").append(toIndentedString(refId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

