/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestDefaultReviewersRequestSourceMatcher;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestRefMatcher;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestRequiredBuildConditionSetRequest
 */
@JsonPropertyOrder({
  RestRequiredBuildConditionSetRequest.JSON_PROPERTY_BUILD_PARENT_KEYS,
  RestRequiredBuildConditionSetRequest.JSON_PROPERTY_EXEMPT_REF_MATCHER,
  RestRequiredBuildConditionSetRequest.JSON_PROPERTY_REF_MATCHER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestRequiredBuildConditionSetRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_BUILD_PARENT_KEYS = "buildParentKeys";
  @jakarta.annotation.Nonnull
  private List<String> buildParentKeys = new ArrayList<>();

  public static final String JSON_PROPERTY_EXEMPT_REF_MATCHER = "exemptRefMatcher";
  @jakarta.annotation.Nullable
  private RestRefMatcher exemptRefMatcher;

  public static final String JSON_PROPERTY_REF_MATCHER = "refMatcher";
  @jakarta.annotation.Nonnull
  private RestDefaultReviewersRequestSourceMatcher refMatcher;

  public RestRequiredBuildConditionSetRequest() {
  }

  public RestRequiredBuildConditionSetRequest buildParentKeys(@jakarta.annotation.Nonnull List<String> buildParentKeys) {
    
    this.buildParentKeys = buildParentKeys;
    return this;
  }

  public RestRequiredBuildConditionSetRequest addBuildParentKeysItem(String buildParentKeysItem) {
    if (this.buildParentKeys == null) {
      this.buildParentKeys = new ArrayList<>();
    }
    this.buildParentKeys.add(buildParentKeysItem);
    return this;
  }

  /**
   * A non-empty list of build parent keys that require green builds for this merge check to pass
   * @return buildParentKeys
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BUILD_PARENT_KEYS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getBuildParentKeys() {
    return buildParentKeys;
  }


  @JsonProperty(JSON_PROPERTY_BUILD_PARENT_KEYS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBuildParentKeys(@jakarta.annotation.Nonnull List<String> buildParentKeys) {
    this.buildParentKeys = buildParentKeys;
  }

  public RestRequiredBuildConditionSetRequest exemptRefMatcher(@jakarta.annotation.Nullable RestRefMatcher exemptRefMatcher) {
    
    this.exemptRefMatcher = exemptRefMatcher;
    return this;
  }

  /**
   * Get exemptRefMatcher
   * @return exemptRefMatcher
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXEMPT_REF_MATCHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestRefMatcher getExemptRefMatcher() {
    return exemptRefMatcher;
  }


  @JsonProperty(JSON_PROPERTY_EXEMPT_REF_MATCHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExemptRefMatcher(@jakarta.annotation.Nullable RestRefMatcher exemptRefMatcher) {
    this.exemptRefMatcher = exemptRefMatcher;
  }

  public RestRequiredBuildConditionSetRequest refMatcher(@jakarta.annotation.Nonnull RestDefaultReviewersRequestSourceMatcher refMatcher) {
    
    this.refMatcher = refMatcher;
    return this;
  }

  /**
   * Get refMatcher
   * @return refMatcher
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REF_MATCHER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RestDefaultReviewersRequestSourceMatcher getRefMatcher() {
    return refMatcher;
  }


  @JsonProperty(JSON_PROPERTY_REF_MATCHER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRefMatcher(@jakarta.annotation.Nonnull RestDefaultReviewersRequestSourceMatcher refMatcher) {
    this.refMatcher = refMatcher;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestRequiredBuildConditionSetRequest restRequiredBuildConditionSetRequest = (RestRequiredBuildConditionSetRequest) o;
    return Objects.equals(this.buildParentKeys, restRequiredBuildConditionSetRequest.buildParentKeys) &&
        Objects.equals(this.exemptRefMatcher, restRequiredBuildConditionSetRequest.exemptRefMatcher) &&
        Objects.equals(this.refMatcher, restRequiredBuildConditionSetRequest.refMatcher);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buildParentKeys, exemptRefMatcher, refMatcher);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestRequiredBuildConditionSetRequest {\n");
    sb.append("    buildParentKeys: ").append(toIndentedString(buildParentKeys)).append("\n");
    sb.append("    exemptRefMatcher: ").append(toIndentedString(exemptRefMatcher)).append("\n");
    sb.append("    refMatcher: ").append(toIndentedString(refMatcher)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

