/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestRepositorySelector;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.LinkedHashSet;
import java.util.Set;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestExportRequestRepositoriesRequest
 */
@JsonPropertyOrder({
  RestExportRequestRepositoriesRequest.JSON_PROPERTY_INCLUDES
})
@JsonTypeName("RestExportRequest_repositoriesRequest")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestExportRequestRepositoriesRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_INCLUDES = "includes";
  @jakarta.annotation.Nonnull
  private Set<RestRepositorySelector> includes = new LinkedHashSet<>();

  public RestExportRequestRepositoriesRequest() {
  }

  public RestExportRequestRepositoriesRequest includes(@jakarta.annotation.Nonnull Set<RestRepositorySelector> includes) {
    
    this.includes = includes;
    return this;
  }

  public RestExportRequestRepositoriesRequest addIncludesItem(RestRepositorySelector includesItem) {
    if (this.includes == null) {
      this.includes = new LinkedHashSet<>();
    }
    this.includes.add(includesItem);
    return this;
  }

  /**
   * Get includes
   * @return includes
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INCLUDES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Set<RestRepositorySelector> getIncludes() {
    return includes;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_INCLUDES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIncludes(@jakarta.annotation.Nonnull Set<RestRepositorySelector> includes) {
    this.includes = includes;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestExportRequestRepositoriesRequest restExportRequestRepositoriesRequest = (RestExportRequestRepositoriesRequest) o;
    return Objects.equals(this.includes, restExportRequestRepositoriesRequest.includes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(includes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestExportRequestRepositoriesRequest {\n");
    sb.append("    includes: ").append(toIndentedString(includes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

