/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.boehringer.componentcatalog.client.bitbucket.v89.model.RestExportRequestRepositoriesRequest;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RestExportRequest
 */
@JsonPropertyOrder({
  RestExportRequest.JSON_PROPERTY_EXPORT_LOCATION,
  RestExportRequest.JSON_PROPERTY_REPOSITORIES_REQUEST
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RestExportRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_EXPORT_LOCATION = "exportLocation";
  @jakarta.annotation.Nullable
  private String exportLocation;

  public static final String JSON_PROPERTY_REPOSITORIES_REQUEST = "repositoriesRequest";
  @jakarta.annotation.Nonnull
  private RestExportRequestRepositoriesRequest repositoriesRequest;

  public RestExportRequest() {
  }

  public RestExportRequest exportLocation(@jakarta.annotation.Nullable String exportLocation) {
    
    this.exportLocation = exportLocation;
    return this;
  }

  /**
   * Get exportLocation
   * @return exportLocation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPORT_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExportLocation() {
    return exportLocation;
  }


  @JsonProperty(JSON_PROPERTY_EXPORT_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExportLocation(@jakarta.annotation.Nullable String exportLocation) {
    this.exportLocation = exportLocation;
  }

  public RestExportRequest repositoriesRequest(@jakarta.annotation.Nonnull RestExportRequestRepositoriesRequest repositoriesRequest) {
    
    this.repositoriesRequest = repositoriesRequest;
    return this;
  }

  /**
   * Get repositoriesRequest
   * @return repositoriesRequest
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REPOSITORIES_REQUEST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RestExportRequestRepositoriesRequest getRepositoriesRequest() {
    return repositoriesRequest;
  }


  @JsonProperty(JSON_PROPERTY_REPOSITORIES_REQUEST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRepositoriesRequest(@jakarta.annotation.Nonnull RestExportRequestRepositoriesRequest repositoriesRequest) {
    this.repositoriesRequest = repositoriesRequest;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestExportRequest restExportRequest = (RestExportRequest) o;
    return Objects.equals(this.exportLocation, restExportRequest.exportLocation) &&
        Objects.equals(this.repositoriesRequest, restExportRequest.repositoriesRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exportLocation, repositoriesRequest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestExportRequest {\n");
    sb.append("    exportLocation: ").append(toIndentedString(exportLocation)).append("\n");
    sb.append("    repositoriesRequest: ").append(toIndentedString(repositoriesRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

