/*
 * Bitbucket Data Center
 * This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).
 *
 * The version of the OpenAPI document: 8.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boehringer.componentcatalog.client.bitbucket.v89.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UserPasswordUpdate
 */
@JsonPropertyOrder({
  UserPasswordUpdate.JSON_PROPERTY_OLD_PASSWORD,
  UserPasswordUpdate.JSON_PROPERTY_PASSWORD,
  UserPasswordUpdate.JSON_PROPERTY_PASSWORD_CONFIRM
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class UserPasswordUpdate implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_OLD_PASSWORD = "oldPassword";
  @jakarta.annotation.Nullable
  private String oldPassword;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  @jakarta.annotation.Nullable
  private String password;

  public static final String JSON_PROPERTY_PASSWORD_CONFIRM = "passwordConfirm";
  @jakarta.annotation.Nullable
  private String passwordConfirm;

  public UserPasswordUpdate() {
  }

  public UserPasswordUpdate oldPassword(@jakarta.annotation.Nullable String oldPassword) {
    
    this.oldPassword = oldPassword;
    return this;
  }

  /**
   * Get oldPassword
   * @return oldPassword
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OLD_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOldPassword() {
    return oldPassword;
  }


  @JsonProperty(JSON_PROPERTY_OLD_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOldPassword(@jakarta.annotation.Nullable String oldPassword) {
    this.oldPassword = oldPassword;
  }

  public UserPasswordUpdate password(@jakarta.annotation.Nullable String password) {
    
    this.password = password;
    return this;
  }

  /**
   * Get password
   * @return password
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(@jakarta.annotation.Nullable String password) {
    this.password = password;
  }

  public UserPasswordUpdate passwordConfirm(@jakarta.annotation.Nullable String passwordConfirm) {
    
    this.passwordConfirm = passwordConfirm;
    return this;
  }

  /**
   * Get passwordConfirm
   * @return passwordConfirm
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD_CONFIRM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPasswordConfirm() {
    return passwordConfirm;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD_CONFIRM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPasswordConfirm(@jakarta.annotation.Nullable String passwordConfirm) {
    this.passwordConfirm = passwordConfirm;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserPasswordUpdate userPasswordUpdate = (UserPasswordUpdate) o;
    return Objects.equals(this.oldPassword, userPasswordUpdate.oldPassword) &&
        Objects.equals(this.password, userPasswordUpdate.password) &&
        Objects.equals(this.passwordConfirm, userPasswordUpdate.passwordConfirm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oldPassword, password, passwordConfirm);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserPasswordUpdate {\n");
    sb.append("    oldPassword: ").append(toIndentedString(oldPassword)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    passwordConfirm: ").append(toIndentedString(passwordConfirm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

